# Fish completion for namgen
# Generated automatically by scripts/generate_completions.py

complete -c namgen -s h -l help -d 'Show help message'
complete -c namgen -s c -l count -d 'Number of names to generate' -x
complete -c namgen -s S -l seed -d 'Seed random number generator deterministically' -x
complete -c namgen -s u -l unique -d 'Ensure no duplicate names are emitted'
complete -c namgen -s m -l match -d 'Filter names by regular expression' -x
complete -c namgen -l min-len -d 'Minimum character length' -x
complete -c namgen -l max-len -d 'Maximum character length' -x
complete -c namgen -l compose -d 'Compose multiple generators together' -x
complete -c namgen -l template -d 'Template for composition' -x
complete -c namgen -s i -l interactive -d 'Launch interactive terminal explorer UI'
complete -c namgen -l json -d 'Output results as a JSON array'
complete -c namgen -l csv -d 'Output results in CSV format'
complete -c namgen -l slug -d 'Convert output to lowercase kebab-case slugs'
complete -c namgen -l kebab -d 'Convert output to lowercase kebab-case slugs'
complete -c namgen -s s -l separator -d 'Custom separator string' -x
complete -c namgen -s x -l null-separator -d 'Do not print the separator'
complete -c namgen -l cap -l capcasing -d 'Capitalize first letter of both words'
complete -c namgen -l camel -l camelcasing -d 'CamelCase style'
complete -c namgen -l debug -d 'Enable debug output'
complete -c namgen -s a -l adj -l adj-file -d 'Path to custom adjective file' -r
complete -c namgen -s n -l noun -l noun-file -d 'Path to custom noun file' -r
complete -c namgen -l armour-belts -d 'Generate Armour Belts style names'
complete -c namgen -l armour-boots -d 'Generate Armour Boots style names'
complete -c namgen -l armour-chests -d 'Generate Armour Chests style names'
complete -c namgen -l armour-cloaks -d 'Generate Armour Cloaks style names'
complete -c namgen -l armour-gauntlets -d 'Generate Armour Gauntlets style names'
complete -c namgen -l armour-helmets -d 'Generate Armour Helmets style names'
complete -c namgen -l armour-legs -d 'Generate Armour Legs style names'
complete -c namgen -l armour-pauldrons -d 'Generate Armour Pauldrons style names'
complete -c namgen -l armour-shields -d 'Generate Armour Shields style names'
complete -c namgen -l armour-vambraces -d 'Generate Armour Vambraces style names'
complete -c namgen -l descriptions-aliens -d 'Generate Descriptions Aliens style names'
complete -c namgen -l descriptions-animals -d 'Generate Descriptions Animals style names'
complete -c namgen -l descriptions-armys -d 'Generate Descriptions Armys style names'
complete -c namgen -l descriptions-backstorys -d 'Generate Descriptions Backstorys style names'
complete -c namgen -l descriptions-battlefields -d 'Generate Descriptions Battlefields style names'
complete -c namgen -l descriptions-bows -d 'Generate Descriptions Bows style names'
complete -c namgen -l descriptions-castles -d 'Generate Descriptions Castles style names'
complete -c namgen -l descriptions-characters -d 'Generate Descriptions Characters style names'
complete -c namgen -l descriptions-citys -d 'Generate Descriptions Citys style names'
complete -c namgen -l descriptions-coat_of_arms -d 'Generate Descriptions Coat Of Arms style names'
complete -c namgen -l descriptions-constellations -d 'Generate Descriptions Constellations style names'
complete -c namgen -l descriptions-countrys -d 'Generate Descriptions Countrys style names'
complete -c namgen -l descriptions-diseases -d 'Generate Descriptions Diseases style names'
complete -c namgen -l descriptions-dragons -d 'Generate Descriptions Dragons style names'
complete -c namgen -l descriptions-dungeons -d 'Generate Descriptions Dungeons style names'
complete -c namgen -l descriptions-dyings -d 'Generate Descriptions Dyings style names'
complete -c namgen -l descriptions-fancy_clothings -d 'Generate Descriptions Fancy Clothings style names'
complete -c namgen -l descriptions-flags -d 'Generate Descriptions Flags style names'
complete -c namgen -l descriptions-gems -d 'Generate Descriptions Gems style names'
complete -c namgen -l descriptions-ghost_towns -d 'Generate Descriptions Ghost Towns style names'
complete -c namgen -l descriptions-gods -d 'Generate Descriptions Gods style names'
complete -c namgen -l descriptions-hand_gestures -d 'Generate Descriptions Hand Gestures style names'
complete -c namgen -l descriptions-holidays -d 'Generate Descriptions Holidays style names'
complete -c namgen -l descriptions-houses -d 'Generate Descriptions Houses style names'
complete -c namgen -l descriptions-humanoids -d 'Generate Descriptions Humanoids style names'
complete -c namgen -l descriptions-laws -d 'Generate Descriptions Laws style names'
complete -c namgen -l descriptions-leather_armors -d 'Generate Descriptions Leather Armors style names'
complete -c namgen -l descriptions-martial_arts -d 'Generate Descriptions Martial Arts style names'
complete -c namgen -l descriptions-medieval_clothings -d 'Generate Descriptions Medieval Clothings style names'
complete -c namgen -l descriptions-monuments -d 'Generate Descriptions Monuments style names'
complete -c namgen -l descriptions-pains -d 'Generate Descriptions Pains style names'
complete -c namgen -l descriptions-personalitys -d 'Generate Descriptions Personalitys style names'
complete -c namgen -l descriptions-pistols -d 'Generate Descriptions Pistols style names'
complete -c namgen -l descriptions-planets -d 'Generate Descriptions Planets style names'
complete -c namgen -l descriptions-plants -d 'Generate Descriptions Plants style names'
complete -c namgen -l descriptions-plate_armors -d 'Generate Descriptions Plate Armors style names'
complete -c namgen -l descriptions-plots -d 'Generate Descriptions Plots style names'
complete -c namgen -l descriptions-pokemons -d 'Generate Descriptions Pokemons style names'
complete -c namgen -l descriptions-potions -d 'Generate Descriptions Potions style names'
complete -c namgen -l descriptions-prophecys -d 'Generate fantasy prophecy style descriptions'
complete -c namgen -l descriptions-quests -d 'Generate Descriptions Quests style names'
complete -c namgen -l descriptions-rag_clothings -d 'Generate Descriptions Rag Clothings style names'
complete -c namgen -l descriptions-rifles -d 'Generate Descriptions Rifles style names'
complete -c namgen -l descriptions-school_uniforms -d 'Generate Descriptions School Uniforms style names'
complete -c namgen -l descriptions-shields -d 'Generate Descriptions Shields style names'
complete -c namgen -l descriptions-shotguns -d 'Generate Descriptions Shotguns style names'
complete -c namgen -l descriptions-societys -d 'Generate Descriptions Societys style names'
complete -c namgen -l descriptions-spells -d 'Generate Descriptions Spells style names'
complete -c namgen -l descriptions-staffs -d 'Generate Descriptions Staffs style names'
complete -c namgen -l descriptions-taverns -d 'Generate Descriptions Taverns style names'
complete -c namgen -l descriptions-towns -d 'Generate Descriptions Towns style names'
complete -c namgen -l descriptions-traditions -d 'Generate Descriptions Traditions style names'
complete -c namgen -l descriptions-wands -d 'Generate Descriptions Wands style names'
complete -c namgen -l descriptions-weapons -d 'Generate Descriptions Weapons style names'
complete -c namgen -l destiny-awokens -d 'Generate Destiny Awokens style names'
complete -c namgen -l destiny-cabals -d 'Generate Destiny Cabals style names'
complete -c namgen -l destiny-exos -d 'Generate Destiny Exos style names'
complete -c namgen -l destiny-fallens -d 'Generate Destiny Fallens style names'
complete -c namgen -l destiny-hives -d 'Generate Destiny Hives style names'
complete -c namgen -l destiny-humans -d 'Generate Destiny Humans style names'
complete -c namgen -l destiny-vexs -d 'Generate Destiny Vexs style names'
complete -c namgen -l diablo-angels -d 'Generate Diablo Angels style names'
complete -c namgen -l diablo-demons -d 'Generate Diablo Demons style names'
complete -c namgen -l diablo-khazras -d 'Generate Diablo Khazras style names'
complete -c namgen -l diablo-nephalems -d 'Generate Diablo Nephalems style names'
complete -c namgen -l doctor_who-daleks -d 'Generate Doctor Who Daleks style names'
complete -c namgen -l doctor_who-gallifreyans -d 'Generate Doctor Who Gallifreyans style names'
complete -c namgen -l doctor_who-ice_warriors -d 'Generate Doctor Who Ice Warriors style names'
complete -c namgen -l doctor_who-raxacoricofallapatorians -d 'Generate Doctor Who Raxacoricofallapatorians style names'
complete -c namgen -l doctor_who-silurians -d 'Generate Doctor Who Silurians style names'
complete -c namgen -l doctor_who-sontarans -d 'Generate Doctor Who Sontarans style names'
complete -c namgen -l doctor_who-zygons -d 'Generate Doctor Who Zygons style names'
complete -c namgen -l dragon_age-dwarfs -d 'Generate Dragon Age Dwarfs style names'
complete -c namgen -l dragon_age-elfs -d 'Generate Dragon Age Elfs style names'
complete -c namgen -l dragon_age-humans -d 'Generate Dragon Age Humans style names'
complete -c namgen -l dragon_age-qunaris -d 'Generate Dragon Age Qunaris style names'
complete -c namgen -l dragon_ball-frieza_clans -d 'Generate Dragon Ball Frieza Clans style names'
complete -c namgen -l dragon_ball-hakaishins -d 'Generate Dragon Ball Hakaishins style names'
complete -c namgen -l dragon_ball-humans -d 'Generate Dragon Ball Humans style names'
complete -c namgen -l dragon_ball-others -d 'Generate Dragon Ball Others style names'
complete -c namgen -l dragon_ball-saiyans -d 'Generate Dragon Ball Saiyans style names'
complete -c namgen -l dragon_ball-skians -d 'Generate Dragon Ball Skians style names'
complete -c namgen -l dragon_ball-tuffles -d 'Generate Dragon Ball Tuffles style names'
complete -c namgen -l dungeon_and_dragons-devas -d 'Generate Dungeon And Dragons Devas style names'
complete -c namgen -l dungeon_and_dragons-dragonborns -d 'Generate Dungeon And Dragons Dragonborns style names'
complete -c namgen -l dungeon_and_dragons-drows -d 'Generate Dungeon And Dragons Drows style names'
complete -c namgen -l dungeon_and_dragons-dwarfs -d 'Generate Dungeon And Dragons Dwarfs style names'
complete -c namgen -l dungeon_and_dragons-eladrins -d 'Generate Dungeon And Dragons Eladrins style names'
complete -c namgen -l dungeon_and_dragons-elfs -d 'Generate Dungeon And Dragons Elfs style names'
complete -c namgen -l dungeon_and_dragons-githzerais -d 'Generate Dungeon And Dragons Githzerais style names'
complete -c namgen -l dungeon_and_dragons-gnomes -d 'Generate Dungeon And Dragons Gnomes style names'
complete -c namgen -l dungeon_and_dragons-goliaths -d 'Generate Dungeon And Dragons Goliaths style names'
complete -c namgen -l dungeon_and_dragons-half_elfs -d 'Generate Dungeon And Dragons Half Elfs style names'
complete -c namgen -l dungeon_and_dragons-half_orcs -d 'Generate Dungeon And Dragons Half Orcs style names'
complete -c namgen -l dungeon_and_dragons-halflings -d 'Generate Dungeon And Dragons Halflings style names'
complete -c namgen -l dungeon_and_dragons-humans -d 'Generate Dungeon And Dragons Humans style names'
complete -c namgen -l dungeon_and_dragons-minotaurs -d 'Generate Dungeon And Dragons Minotaurs style names'
complete -c namgen -l dungeon_and_dragons-shardminds -d 'Generate Dungeon And Dragons Shardminds style names'
complete -c namgen -l dungeon_and_dragons-shifters -d 'Generate Dungeon And Dragons Shifters style names'
complete -c namgen -l dungeon_and_dragons-tieflings -d 'Generate Dungeon And Dragons Tieflings style names'
complete -c namgen -l dungeon_and_dragons-wildens -d 'Generate Dungeon And Dragons Wildens style names'
complete -c namgen -l elder_scrolls-altmers -d 'Generate Elder Scrolls Altmers style names'
complete -c namgen -l elder_scrolls-argonians -d 'Generate Elder Scrolls Argonians style names'
complete -c namgen -l elder_scrolls-bosmers -d 'Generate Elder Scrolls Bosmers style names'
complete -c namgen -l elder_scrolls-bretons -d 'Generate Elder Scrolls Bretons style names'
complete -c namgen -l elder_scrolls-daedrics -d 'Generate Elder Scrolls Daedrics style names'
complete -c namgen -l elder_scrolls-dragons -d 'Generate Elder Scrolls Dragons style names'
complete -c namgen -l elder_scrolls-dunmers -d 'Generate Elder Scrolls Dunmers style names'
complete -c namgen -l elder_scrolls-dwemers -d 'Generate Elder Scrolls Dwemers style names'
complete -c namgen -l elder_scrolls-falmers -d 'Generate Elder Scrolls Falmers style names'
complete -c namgen -l elder_scrolls-forsworns -d 'Generate Elder Scrolls Forsworns style names'
complete -c namgen -l elder_scrolls-imperials -d 'Generate Elder Scrolls Imperials style names'
complete -c namgen -l elder_scrolls-khajiits -d 'Generate Elder Scrolls Khajiits style names'
complete -c namgen -l elder_scrolls-nords -d 'Generate Elder Scrolls Nords style names'
complete -c namgen -l elder_scrolls-orc -d 'Generate Elder Scrolls Orc style names'
complete -c namgen -l elder_scrolls-redguards -d 'Generate Elder Scrolls Redguards style names'
complete -c namgen -l elder_scrolls-spriggans -d 'Generate Elder Scrolls Spriggans style names'
complete -c namgen -l eve_online-amarrs -d 'Generate Eve Online Amarrs style names'
complete -c namgen -l eve_online-caldaris -d 'Generate Eve Online Caldaris style names'
complete -c namgen -l eve_online-gallentes -d 'Generate Eve Online Gallentes style names'
complete -c namgen -l eve_online-minmatars -d 'Generate Eve Online Minmatars style names'
complete -c namgen -l fantasy-aliens -d 'Generate Fantasy Aliens style names'
complete -c namgen -l fantasy-amazons -d 'Generate Fantasy Amazons style names'
complete -c namgen -l fantasy-angels -d 'Generate Fantasy Angels style names'
complete -c namgen -l fantasy-animal_species -d 'Generate Fantasy Animal Species style names'
complete -c namgen -l fantasy-animatronics -d 'Generate Fantasy Animatronics style names'
complete -c namgen -l fantasy-apocalypse_mutants -d 'Generate Fantasy Apocalypse Mutants style names'
complete -c namgen -l fantasy-bandits -d 'Generate Fantasy Bandits style names'
complete -c namgen -l fantasy-barbarians -d 'Generate Fantasy Barbarians style names'
complete -c namgen -l fantasy-bounty_hunters -d 'Generate Fantasy Bounty Hunters style names'
complete -c namgen -l fantasy-cat_people_nekojins -d 'Generate Fantasy Cat People Nekojins style names'
complete -c namgen -l fantasy-cavemens -d 'Generate Fantasy Cavemens style names'
complete -c namgen -l fantasy-centaurs -d 'Generate Fantasy Centaurs style names'
complete -c namgen -l fantasy-christmas_elfs -d 'Generate Fantasy Christmas Elfs style names'
complete -c namgen -l fantasy-codes -d 'Generate Fantasy Codes style names'
complete -c namgen -l fantasy-cowboys -d 'Generate Fantasy Cowboys style names'
complete -c namgen -l fantasy-creatures -d 'Generate Fantasy Creatures style names'
complete -c namgen -l fantasy-deaths -d 'Generate Fantasy Deaths style names'
complete -c namgen -l fantasy-demons -d 'Generate Fantasy Demons style names'
complete -c namgen -l fantasy-detectives -d 'Generate Fantasy Detectives style names'
complete -c namgen -l fantasy-dragons -d 'Generate Fantasy Dragons style names'
complete -c namgen -l fantasy-dryads -d 'Generate Fantasy Dryads style names'
complete -c namgen -l fantasy-dwarfs -d 'Generate Fantasy Dwarfs style names'
complete -c namgen -l fantasy-elementals -d 'Generate Fantasy Elementals style names'
complete -c namgen -l fantasy-elfs -d 'Generate Fantasy Elfs style names'
complete -c namgen -l fantasy-ents -d 'Generate Fantasy Ents style names'
complete -c namgen -l fantasy-evils -d 'Generate Fantasy Evils style names'
complete -c namgen -l fantasy-fairys -d 'Generate Fantasy Fairys style names'
complete -c namgen -l fantasy-fantasy_animals -d 'Generate Fantasy Animals style names'
complete -c namgen -l fantasy-fantasy_races -d 'Generate Fantasy Races style names'
complete -c namgen -l fantasy-fantasy_surnames -d 'Generate Fantasy Surnames style names'
complete -c namgen -l fantasy-fursonas -d 'Generate Fantasy Fursonas style names'
complete -c namgen -l fantasy-futuristics -d 'Generate Fantasy Futuristics style names'
complete -c namgen -l fantasy-ghost_classifications -d 'Generate Fantasy Ghost Classifications style names'
complete -c namgen -l fantasy-ghosts -d 'Generate Fantasy Ghosts style names'
complete -c namgen -l fantasy-giants -d 'Generate Fantasy Giants style names'
complete -c namgen -l fantasy-gnolls -d 'Generate Fantasy Gnolls style names'
complete -c namgen -l fantasy-gnomes -d 'Generate Fantasy Gnomes style names'
complete -c namgen -l fantasy-goblins -d 'Generate Fantasy Goblins style names'
complete -c namgen -l fantasy-gods -d 'Generate Fantasy Gods style names'
complete -c namgen -l fantasy-gorgons -d 'Generate Fantasy Gorgons style names'
complete -c namgen -l fantasy-griffins -d 'Generate Fantasy Griffins style names'
complete -c namgen -l fantasy-half_elfs -d 'Generate Fantasy Half Elfs style names'
complete -c namgen -l fantasy-harpys -d 'Generate Fantasy Harpys style names'
complete -c namgen -l fantasy-heros -d 'Generate Fantasy Heros style names'
complete -c namgen -l fantasy-hobbits -d 'Generate Fantasy Hobbits style names'
complete -c namgen -l fantasy-horses -d 'Generate Fantasy Horses style names'
complete -c namgen -l fantasy-imps -d 'Generate Fantasy Imps style names'
complete -c namgen -l fantasy-kaijus -d 'Generate Fantasy Kaijus style names'
complete -c namgen -l fantasy-killers -d 'Generate Fantasy Killers style names'
complete -c namgen -l fantasy-knights -d 'Generate Fantasy Knights style names'
complete -c namgen -l fantasy-kobolds -d 'Generate Fantasy Kobolds style names'
complete -c namgen -l fantasy-lamias -d 'Generate Fantasy Lamias style names'
complete -c namgen -l fantasy-lichs -d 'Generate Fantasy Lichs style names'
complete -c namgen -l fantasy-mechas -d 'Generate Fantasy Mechas style names'
complete -c namgen -l fantasy-medievals -d 'Generate Fantasy Medievals style names'
complete -c namgen -l fantasy-mermaids -d 'Generate Fantasy Mermaids style names'
complete -c namgen -l fantasy-minotaurs -d 'Generate Fantasy Minotaurs style names'
complete -c namgen -l fantasy-mobsters -d 'Generate Fantasy Mobsters style names'
complete -c namgen -l fantasy-monsters -d 'Generate Fantasy Monsters style names'
complete -c namgen -l fantasy-mutant_species -d 'Generate Fantasy Mutant Species style names'
complete -c namgen -l fantasy-nagas -d 'Generate Fantasy Nagas style names'
complete -c namgen -l fantasy-necromancers -d 'Generate Fantasy Necromancers style names'
complete -c namgen -l fantasy-nephilims -d 'Generate Fantasy Nephilims style names'
complete -c namgen -l fantasy-ninjas -d 'Generate Fantasy Ninjas style names'
complete -c namgen -l fantasy-nymphs -d 'Generate Fantasy Nymphs style names'
complete -c namgen -l fantasy-ogres -d 'Generate Fantasy Ogres style names'
complete -c namgen -l fantasy-orcs -d 'Generate Fantasy Orcs style names'
complete -c namgen -l fantasy-pegasus -d 'Generate Fantasy Pegasus style names'
complete -c namgen -l fantasy-phoenixs -d 'Generate Fantasy Phoenixs style names'
complete -c namgen -l fantasy-pirates -d 'Generate Fantasy Pirates style names'
complete -c namgen -l fantasy-robots -d 'Generate Fantasy Robots style names'
complete -c namgen -l fantasy-satyr_fauns -d 'Generate Fantasy Satyr Fauns style names'
complete -c namgen -l fantasy-sea_creatures -d 'Generate Fantasy Sea Creatures style names'
complete -c namgen -l fantasy-servants -d 'Generate Fantasy Servants style names'
complete -c namgen -l fantasy-shapeshifters -d 'Generate Fantasy Shapeshifters style names'
complete -c namgen -l fantasy-sirens -d 'Generate Fantasy Sirens style names'
complete -c namgen -l fantasy-slaves -d 'Generate Fantasy Slaves style names'
complete -c namgen -l fantasy-species -d 'Generate Fantasy Species style names'
complete -c namgen -l fantasy-steampunks -d 'Generate Fantasy Steampunks style names'
complete -c namgen -l fantasy-succubus -d 'Generate Fantasy Succubus style names'
complete -c namgen -l fantasy-superhero_teams -d 'Generate Fantasy Superhero Teams style names'
complete -c namgen -l fantasy-sylphs -d 'Generate Fantasy Sylphs style names'
complete -c namgen -l fantasy-taurens -d 'Generate Fantasy Taurens style names'
complete -c namgen -l fantasy-trolls -d 'Generate Fantasy Trolls style names'
complete -c namgen -l fantasy-twins -d 'Generate Fantasy Twins style names'
complete -c namgen -l fantasy-unicorns -d 'Generate Fantasy Unicorns style names'
complete -c namgen -l fantasy-valkyries -d 'Generate Fantasy Valkyries style names'
complete -c namgen -l fantasy-vampire_clans -d 'Generate Fantasy Vampire Clans style names'
complete -c namgen -l fantasy-vampires -d 'Generate Fantasy Vampires style names'
complete -c namgen -l fantasy-villains -d 'Generate Fantasy Villains style names'
complete -c namgen -l fantasy-warrior_nicknames -d 'Generate Fantasy Warrior Nicknames style names'
complete -c namgen -l fantasy-werewolf_packs -d 'Generate Fantasy Werewolf Packs style names'
complete -c namgen -l fantasy-werewolfs -d 'Generate Fantasy Werewolfs style names'
complete -c namgen -l fantasy-witchs -d 'Generate Fantasy Witchs style names'
complete -c namgen -l fantasy-wizards -d 'Generate Fantasy Wizards style names'
complete -c namgen -l fantasy-zombie_types -d 'Generate Fantasy Zombie Types style names'
complete -c namgen -l final_fantasy-au_ras -d 'Generate Final Fantasy Au Ras style names'
complete -c namgen -l final_fantasy-elezens -d 'Generate Final Fantasy Elezens style names'
complete -c namgen -l final_fantasy-hyurs -d 'Generate Final Fantasy Hyurs style names'
complete -c namgen -l final_fantasy-lalafells -d 'Generate Final Fantasy Lalafells style names'
complete -c namgen -l final_fantasy-miqotes -d 'Generate Final Fantasy Miqotes style names'
complete -c namgen -l final_fantasy-roegadyns -d 'Generate Final Fantasy Roegadyns style names'
complete -c namgen -l game_of_thrones-dothrakis -d 'Generate Game Of Thrones Dothrakis style names'
complete -c namgen -l game_of_thrones-free_citys -d 'Generate Game Of Thrones Free Citys style names'
complete -c namgen -l game_of_thrones-free_folks -d 'Generate Game Of Thrones Free Folks style names'
complete -c namgen -l game_of_thrones-ghiscaris -d 'Generate Game Of Thrones Ghiscaris style names'
complete -c namgen -l game_of_thrones-mountain_clans -d 'Generate Game Of Thrones Mountain Clans style names'
complete -c namgen -l game_of_thrones-nicknames -d 'Generate Game Of Thrones Nicknames style names'
complete -c namgen -l game_of_thrones-summer_islanders -d 'Generate Game Of Thrones Summer Islanders style names'
complete -c namgen -l game_of_thrones-unsullieds -d 'Generate Game Of Thrones Unsullieds style names'
complete -c namgen -l game_of_thrones-valyrians -d 'Generate Game Of Thrones Valyrians style names'
complete -c namgen -l game_of_thrones-westeros -d 'Generate Game Of Thrones Westeros style names'
complete -c namgen -l guild_wars-asuras -d 'Generate Guild Wars Asuras style names'
complete -c namgen -l guild_wars-charrs -d 'Generate Guild Wars Charrs style names'
complete -c namgen -l guild_wars-human -d 'Generate Guild Wars Human style names'
complete -c namgen -l guild_wars-norns -d 'Generate Guild Wars Norns style names'
complete -c namgen -l guild_wars-sylvaris -d 'Generate Guild Wars Sylvaris style names'
complete -c namgen -l halo-forerunners -d 'Generate Halo Forerunners style names'
complete -c namgen -l halo-huragoks -d 'Generate Halo Huragoks style names'
complete -c namgen -l halo-jiralhanaes -d 'Generate Halo Jiralhanaes style names'
complete -c namgen -l halo-kig_yars -d 'Generate Halo Kig Yars style names'
complete -c namgen -l halo-mgalekgolos -d 'Generate Halo Mgalekgolos style names'
complete -c namgen -l halo-san_shyuums -d 'Generate Halo San Shyuums style names'
complete -c namgen -l halo-sangheilis -d 'Generate Halo Sangheilis style names'
complete -c namgen -l halo-unggoys -d 'Generate Halo Unggoys style names'
complete -c namgen -l harry_potter-dragon_species -d 'Generate Harry Potter Dragon Species style names'
complete -c namgen -l harry_potter-goblins -d 'Generate Harry Potter Goblins style names'
complete -c namgen -l harry_potter-hippogriffs -d 'Generate Harry Potter Hippogriffs style names'
complete -c namgen -l harry_potter-house_elfs -d 'Generate Harry Potter House Elfs style names'
complete -c namgen -l harry_potter-winged_horses -d 'Generate Harry Potter Winged Horses style names'
complete -c namgen -l inheritance_cycle-dragons -d 'Generate Inheritance Cycle Dragons style names'
complete -c namgen -l inheritance_cycle-dwarfs -d 'Generate Inheritance Cycle Dwarfs style names'
complete -c namgen -l inheritance_cycle-elfs -d 'Generate Inheritance Cycle Elfs style names'
complete -c namgen -l inheritance_cycle-humans -d 'Generate Inheritance Cycle Humans style names'
complete -c namgen -l inheritance_cycle-urgals -d 'Generate Inheritance Cycle Urgals style names'
complete -c namgen -l legend_of_zelda-anoukis -d 'Generate Legend Of Zelda Anoukis style names'
complete -c namgen -l legend_of_zelda-deitys -d 'Generate Legend Of Zelda Deitys style names'
complete -c namgen -l legend_of_zelda-dekus -d 'Generate Legend Of Zelda Dekus style names'
complete -c namgen -l legend_of_zelda-fairys -d 'Generate Legend Of Zelda Fairys style names'
complete -c namgen -l legend_of_zelda-gerudos -d 'Generate Legend Of Zelda Gerudos style names'
complete -c namgen -l legend_of_zelda-gorons -d 'Generate Legend Of Zelda Gorons style names'
complete -c namgen -l legend_of_zelda-humans -d 'Generate Legend Of Zelda Humans style names'
complete -c namgen -l legend_of_zelda-korok_kokiris -d 'Generate Legend Of Zelda Korok Kokiris style names'
complete -c namgen -l legend_of_zelda-minishs -d 'Generate Legend Of Zelda Minishs style names'
complete -c namgen -l legend_of_zelda-zoras -d 'Generate Legend Of Zelda Zoras style names'
complete -c namgen -l lord_of_the_rings-dwarfs -d 'Generate Lord Of The Rings Dwarfs style names'
complete -c namgen -l lord_of_the_rings-elfs -d 'Generate Lord of the Rings elf style names'
complete -c namgen -l lord_of_the_rings-hobbits -d 'Generate Lord Of The Rings Hobbits style names'
complete -c namgen -l lord_of_the_rings-humans -d 'Generate Lord Of The Rings Humans style names'
complete -c namgen -l lord_of_the_rings-maiars -d 'Generate Lord Of The Rings Maiars style names'
complete -c namgen -l lord_of_the_rings-orcs -d 'Generate Lord Of The Rings Orcs style names'
complete -c namgen -l lord_of_the_rings_online-beorning -d 'Generate Lord Of The Rings Online Beorning style names'
complete -c namgen -l lord_of_the_rings_online-dwarf -d 'Generate Lord Of The Rings Online Dwarf style names'
complete -c namgen -l lord_of_the_rings_online-elf -d 'Generate Lord Of The Rings Online Elf style names'
complete -c namgen -l lord_of_the_rings_online-hobbit -d 'Generate Lord Of The Rings Online Hobbit style names'
complete -c namgen -l lord_of_the_rings_online-human -d 'Generate Lord Of The Rings Online Human style names'
complete -c namgen -l mass_effect-asaris -d 'Generate Mass Effect Asaris style names'
complete -c namgen -l mass_effect-batarians -d 'Generate Mass Effect Batarians style names'
complete -c namgen -l mass_effect-drells -d 'Generate Mass Effect Drells style names'
complete -c namgen -l mass_effect-geths -d 'Generate Mass Effect Geths style names'
complete -c namgen -l mass_effect-humans -d 'Generate Mass Effect Humans style names'
complete -c namgen -l mass_effect-krogans -d 'Generate Mass Effect Krogans style names'
complete -c namgen -l mass_effect-quarians -d 'Generate Mass Effect Quarians style names'
complete -c namgen -l mass_effect-salarians -d 'Generate Mass Effect Salarians style names'
complete -c namgen -l mass_effect-turians -d 'Generate Mass Effect Turians style names'
complete -c namgen -l military-itu -d 'Generate Military Itu style names'
complete -c namgen -l military-nato -d 'Generate Military Nato style names'
complete -c namgen -l military-numeric -d 'Generate Military Numeric style names'
complete -c namgen -l military-royal_air_force -d 'Generate Military Royal Air Force style names'
complete -c namgen -l military-royal_navy -d 'Generate Royal Navy military call-sign style names'
complete -c namgen -l military-signalese -d 'Generate Military Signalese style names'
complete -c namgen -l military-telegram -d 'Generate Military Telegram style names'
complete -c namgen -l military-united_states -d 'Generate United States military NATO phonetic call-signs'
complete -c namgen -l miscellaneous-afterlifes -d 'Generate Miscellaneous Afterlifes style names'
complete -c namgen -l miscellaneous-airplanes -d 'Generate Miscellaneous Airplanes style names'
complete -c namgen -l miscellaneous-airships -d 'Generate Miscellaneous Airships style names'
complete -c namgen -l miscellaneous-alliances -d 'Generate Miscellaneous Alliances style names'
complete -c namgen -l miscellaneous-animal_groups -d 'Generate Miscellaneous Animal Groups style names'
complete -c namgen -l miscellaneous-anime_attacks -d 'Generate Miscellaneous Anime Attacks style names'
complete -c namgen -l miscellaneous-apocalypses -d 'Generate Miscellaneous Apocalypses style names'
complete -c namgen -l miscellaneous-armys -d 'Generate Miscellaneous Armys style names'
complete -c namgen -l miscellaneous-artifacts -d 'Generate Miscellaneous Artifacts style names'
complete -c namgen -l miscellaneous-attack_moves -d 'Generate Miscellaneous Attack Moves style names'
complete -c namgen -l miscellaneous-awards -d 'Generate Miscellaneous Awards style names'
complete -c namgen -l miscellaneous-bands -d 'Generate Miscellaneous Bands style names'
complete -c namgen -l miscellaneous-battles -d 'Generate Miscellaneous Battles style names'
complete -c namgen -l miscellaneous-birds -d 'Generate Miscellaneous Birds style names'
complete -c namgen -l miscellaneous-board_games -d 'Generate Miscellaneous Board Games style names'
complete -c namgen -l miscellaneous-book_titles -d 'Generate Miscellaneous Book Titles style names'
complete -c namgen -l miscellaneous-bouquets -d 'Generate Miscellaneous Bouquets style names'
complete -c namgen -l miscellaneous-brands -d 'Generate Miscellaneous Brands style names'
complete -c namgen -l miscellaneous-candys -d 'Generate Miscellaneous Candys style names'
complete -c namgen -l miscellaneous-cars -d 'Generate Miscellaneous Cars style names'
complete -c namgen -l miscellaneous-chivalric_orders -d 'Generate Miscellaneous Chivalric Orders style names'
complete -c namgen -l miscellaneous-class -d 'Generate Miscellaneous Class style names'
complete -c namgen -l miscellaneous-clothing_brands -d 'Generate Miscellaneous Clothing Brands style names'
complete -c namgen -l miscellaneous-colors -d 'Generate Miscellaneous Colors style names'
complete -c namgen -l miscellaneous-constellations -d 'Generate Miscellaneous Constellations style names'
complete -c namgen -l miscellaneous-creepypastas -d 'Generate Miscellaneous Creepypastas style names'
complete -c namgen -l miscellaneous-crops -d 'Generate Miscellaneous Crops style names'
complete -c namgen -l miscellaneous-currencys -d 'Generate Miscellaneous Currencys style names'
complete -c namgen -l miscellaneous-dances -d 'Generate Miscellaneous Dances style names'
complete -c namgen -l miscellaneous-dates -d 'Generate Miscellaneous Dates style names'
complete -c namgen -l miscellaneous-dinosaurs -d 'Generate Miscellaneous Dinosaurs style names'
complete -c namgen -l miscellaneous-diseases -d 'Generate Miscellaneous Diseases style names'
complete -c namgen -l miscellaneous-drinks -d 'Generate Miscellaneous Drinks style names'
complete -c namgen -l miscellaneous-drugs -d 'Generate Miscellaneous Drugs style names'
complete -c namgen -l miscellaneous-enchantments -d 'Generate Miscellaneous Enchantments style names'
complete -c namgen -l miscellaneous-energy_types -d 'Generate Miscellaneous Energy Types style names'
complete -c namgen -l miscellaneous-epithets -d 'Generate Miscellaneous Epithets style names'
complete -c namgen -l miscellaneous-evil_groups -d 'Generate Miscellaneous Evil Groups style names'
complete -c namgen -l miscellaneous-foods -d 'Generate Miscellaneous Foods style names'
complete -c namgen -l miscellaneous-fruit_vegetables -d 'Generate Miscellaneous Fruit Vegetables style names'
complete -c namgen -l miscellaneous-fungis -d 'Generate Miscellaneous Fungis style names'
complete -c namgen -l miscellaneous-galaxys -d 'Generate Miscellaneous Galaxys style names'
complete -c namgen -l miscellaneous-game_engines -d 'Generate Miscellaneous Game Engines style names'
complete -c namgen -l miscellaneous-game_soundtracks -d 'Generate Miscellaneous Game Soundtracks style names'
complete -c namgen -l miscellaneous-gangs -d 'Generate Miscellaneous Gangs style names'
complete -c namgen -l miscellaneous-gear_enchantments -d 'Generate Miscellaneous Gear Enchantments style names'
complete -c namgen -l miscellaneous-gem_minerals -d 'Generate Miscellaneous Gem Minerals style names'
complete -c namgen -l miscellaneous-graffiti_tags -d 'Generate Miscellaneous Graffiti Tags style names'
complete -c namgen -l miscellaneous-guilds -d 'Generate Miscellaneous Guilds style names'
complete -c namgen -l miscellaneous-hackers -d 'Generate Miscellaneous Hackers style names'
complete -c namgen -l miscellaneous-heists -d 'Generate Miscellaneous Heists style names'
complete -c namgen -l miscellaneous-helicopters -d 'Generate Miscellaneous Helicopters style names'
complete -c namgen -l miscellaneous-herbs -d 'Generate Miscellaneous Herbs style names'
complete -c namgen -l miscellaneous-holidays -d 'Generate Miscellaneous Holidays style names'
complete -c namgen -l miscellaneous-holy_books -d 'Generate Miscellaneous Holy Books style names'
complete -c namgen -l miscellaneous-human_species -d 'Generate Miscellaneous Human Species style names'
complete -c namgen -l miscellaneous-instruments -d 'Generate Miscellaneous Instruments style names'
complete -c namgen -l miscellaneous-inventions -d 'Generate Miscellaneous Inventions style names'
complete -c namgen -l miscellaneous-jewelrys -d 'Generate Miscellaneous Jewelrys style names'
complete -c namgen -l miscellaneous-languages -d 'Generate Miscellaneous Languages style names'
complete -c namgen -l miscellaneous-love_nicknames -d 'Generate Miscellaneous Love Nicknames style names'
complete -c namgen -l miscellaneous-magazines -d 'Generate Miscellaneous Magazines style names'
complete -c namgen -l miscellaneous-magic_types -d 'Generate Miscellaneous Magic Types style names'
complete -c namgen -l miscellaneous-magical_diseases -d 'Generate Miscellaneous Magical Diseases style names'
complete -c namgen -l miscellaneous-magical_plants -d 'Generate Miscellaneous Magical Plants style names'
complete -c namgen -l miscellaneous-magical_trees -d 'Generate Miscellaneous Magical Trees style names'
complete -c namgen -l miscellaneous-martial_arts -d 'Generate Miscellaneous Martial Arts style names'
complete -c namgen -l miscellaneous-mascots -d 'Generate Miscellaneous Mascots style names'
complete -c namgen -l miscellaneous-medicines -d 'Generate Miscellaneous Medicines style names'
complete -c namgen -l miscellaneous-metals -d 'Generate Miscellaneous Metals style names'
complete -c namgen -l miscellaneous-military_divisions -d 'Generate Miscellaneous Military Divisions style names'
complete -c namgen -l miscellaneous-military_operations -d 'Generate Miscellaneous Military Operations style names'
complete -c namgen -l miscellaneous-military_ranks -d 'Generate Miscellaneous Military Ranks style names'
complete -c namgen -l miscellaneous-military_vehicles -d 'Generate Miscellaneous Military Vehicles style names'
complete -c namgen -l miscellaneous-molecules -d 'Generate Miscellaneous Molecules style names'
complete -c namgen -l miscellaneous-motorcycle_clubs -d 'Generate Miscellaneous Motorcycle Clubs style names'
complete -c namgen -l miscellaneous-mutant_plants -d 'Generate Miscellaneous Mutant Plants style names'
complete -c namgen -l miscellaneous-natural_disasters -d 'Generate Miscellaneous Natural Disasters style names'
complete -c namgen -l miscellaneous-newspapers -d 'Generate Miscellaneous Newspapers style names'
complete -c namgen -l miscellaneous-nicknames -d 'Generate Miscellaneous Nicknames style names'
complete -c namgen -l miscellaneous-noble_houses -d 'Generate Miscellaneous Noble Houses style names'
complete -c namgen -l miscellaneous-pirate_crews -d 'Generate Miscellaneous Pirate Crews style names'
complete -c namgen -l miscellaneous-pirate_ships -d 'Generate Miscellaneous Pirate Ships style names'
complete -c namgen -l miscellaneous-plagues -d 'Generate Miscellaneous Plagues style names'
complete -c namgen -l miscellaneous-plants -d 'Generate Miscellaneous Plants style names'
complete -c namgen -l miscellaneous-poisons -d 'Generate Miscellaneous Poisons style names'
complete -c namgen -l miscellaneous-political_partys -d 'Generate Miscellaneous Political Partys style names'
complete -c namgen -l miscellaneous-post_apocalyptic_societys -d 'Generate Miscellaneous Post Apocalyptic Societys style names'
complete -c namgen -l miscellaneous-potions -d 'Generate Miscellaneous Potions style names'
complete -c namgen -l miscellaneous-professions -d 'Generate Miscellaneous Professions style names'
complete -c namgen -l miscellaneous-racers -d 'Generate Miscellaneous Racers style names'
complete -c namgen -l miscellaneous-railways -d 'Generate Miscellaneous Railways style names'
complete -c namgen -l miscellaneous-ranks -d 'Generate Miscellaneous Ranks style names'
complete -c namgen -l miscellaneous-religions -d 'Generate Miscellaneous Religions style names'
complete -c namgen -l miscellaneous-scientific_creatures -d 'Generate Miscellaneous Scientific Creatures style names'
complete -c namgen -l miscellaneous-ships -d 'Generate Miscellaneous Ships style names'
complete -c namgen -l miscellaneous-siege_engines -d 'Generate Miscellaneous Siege Engines style names'
complete -c namgen -l miscellaneous-softwares -d 'Generate Miscellaneous Softwares style names'
complete -c namgen -l miscellaneous-song_titles -d 'Generate Miscellaneous Song Titles style names'
complete -c namgen -l miscellaneous-space_fleets -d 'Generate Miscellaneous Space Fleets style names'
complete -c namgen -l miscellaneous-spaceships -d 'Generate Miscellaneous Spaceships style names'
complete -c namgen -l miscellaneous-spells -d 'Generate Miscellaneous Spells style names'
complete -c namgen -l miscellaneous-sports -d 'Generate Miscellaneous Sports style names'
complete -c namgen -l miscellaneous-sports_teams -d 'Generate Miscellaneous Sports Teams style names'
complete -c namgen -l miscellaneous-squads -d 'Generate Miscellaneous Squads style names'
complete -c namgen -l miscellaneous-superpowers -d 'Generate Miscellaneous Superpowers style names'
complete -c namgen -l miscellaneous-teleportations -d 'Generate Miscellaneous Teleportations style names'
complete -c namgen -l miscellaneous-thrones -d 'Generate Miscellaneous Thrones style names'
complete -c namgen -l miscellaneous-time_periods -d 'Generate Miscellaneous Time Periods style names'
complete -c namgen -l miscellaneous-titles -d 'Generate Miscellaneous Titles style names'
complete -c namgen -l miscellaneous-tool_nicknames -d 'Generate Miscellaneous Tool Nicknames style names'
complete -c namgen -l miscellaneous-treatys -d 'Generate Miscellaneous Treatys style names'
complete -c namgen -l miscellaneous-trees -d 'Generate Miscellaneous Trees style names'
complete -c namgen -l miscellaneous-tribals -d 'Generate Miscellaneous Tribals style names'
complete -c namgen -l miscellaneous-tribes -d 'Generate Miscellaneous Tribes style names'
complete -c namgen -l miscellaneous-usernames -d 'Generate Miscellaneous Usernames style names'
complete -c namgen -l miscellaneous-vehicles -d 'Generate Miscellaneous Vehicles style names'
complete -c namgen -l miscellaneous-video_games -d 'Generate Miscellaneous Video Games style names'
complete -c namgen -l miscellaneous-vocal_groups -d 'Generate Miscellaneous Vocal Groups style names'
complete -c namgen -l miscellaneous-weapon_abilities -d 'Generate Miscellaneous Weapon Abilities style names'
complete -c namgen -l miscellaneous-web_series -d 'Generate Miscellaneous Web Series style names'
complete -c namgen -l miscellaneous-wines -d 'Generate Miscellaneous Wines style names'
complete -c namgen -l miscellaneous-wrestlers -d 'Generate Miscellaneous Wrestlers style names'
complete -c namgen -l miscellaneous-wrestling_moves -d 'Generate Miscellaneous Wrestling Moves style names'
complete -c namgen -l pathfinder-aasimars -d 'Generate Pathfinder Aasimars style names'
complete -c namgen -l pathfinder-catfolks -d 'Generate Pathfinder Catfolks style names'
complete -c namgen -l pathfinder-drows -d 'Generate Pathfinder Drows style names'
complete -c namgen -l pathfinder-dwarfs -d 'Generate Pathfinder Dwarfs style names'
complete -c namgen -l pathfinder-elfs -d 'Generate Pathfinder Elfs style names'
complete -c namgen -l pathfinder-fetchlings -d 'Generate Pathfinder Fetchlings style names'
complete -c namgen -l pathfinder-gnomes -d 'Generate Pathfinder Gnomes style names'
complete -c namgen -l pathfinder-goblins -d 'Generate Pathfinder Goblins style names'
complete -c namgen -l pathfinder-half_elfs -d 'Generate Pathfinder Half Elfs style names'
complete -c namgen -l pathfinder-half_orcs -d 'Generate Pathfinder Half Orcs style names'
complete -c namgen -l pathfinder-halflings -d 'Generate Pathfinder Halflings style names'
complete -c namgen -l pathfinder-hobgoblins -d 'Generate Pathfinder Hobgoblins style names'
complete -c namgen -l pathfinder-humans -d 'Generate Pathfinder Humans style names'
complete -c namgen -l pathfinder-ifrits -d 'Generate Pathfinder Ifrits style names'
complete -c namgen -l pathfinder-kobolds -d 'Generate Pathfinder Kobolds style names'
complete -c namgen -l pathfinder-orcs -d 'Generate Pathfinder Orcs style names'
complete -c namgen -l pathfinder-oreads -d 'Generate Pathfinder Oreads style names'
complete -c namgen -l pathfinder-ratfolks -d 'Generate Pathfinder Ratfolks style names'
complete -c namgen -l pathfinder-sylphs -d 'Generate Pathfinder Sylphs style names'
complete -c namgen -l pathfinder-tengus -d 'Generate Pathfinder Tengus style names'
complete -c namgen -l pathfinder-tians -d 'Generate Pathfinder Tians style names'
complete -c namgen -l pathfinder-tieflings -d 'Generate Pathfinder Tieflings style names'
complete -c namgen -l pathfinder-undines -d 'Generate Pathfinder Undines style names'
complete -c namgen -l pets-aliens -d 'Generate Pets Aliens style names'
complete -c namgen -l pets-amphibians -d 'Generate Pets Amphibians style names'
complete -c namgen -l pets-bats -d 'Generate Pets Bats style names'
complete -c namgen -l pets-bears -d 'Generate Pets Bears style names'
complete -c namgen -l pets-bird_of_preys -d 'Generate Pets Bird Of Preys style names'
complete -c namgen -l pets-birds -d 'Generate Pets Birds style names'
complete -c namgen -l pets-cats -d 'Generate Pets Cats style names'
complete -c namgen -l pets-cows -d 'Generate Pets Cows style names'
complete -c namgen -l pets-crabs -d 'Generate Pets Crabs style names'
complete -c namgen -l pets-deers -d 'Generate Pets Deers style names'
complete -c namgen -l pets-dogs -d 'Generate Pets Dogs style names'
complete -c namgen -l pets-elephants -d 'Generate Pets Elephants style names'
complete -c namgen -l pets-fishs -d 'Generate Pets Fishs style names'
complete -c namgen -l pets-horses -d 'Generate Pets Horses style names'
complete -c namgen -l pets-insects -d 'Generate Pets Insects style names'
complete -c namgen -l pets-lions -d 'Generate Pets Lions style names'
complete -c namgen -l pets-marine_mammals -d 'Generate Pets Marine Mammals style names'
complete -c namgen -l pets-monkeys -d 'Generate Pets Monkeys style names'
complete -c namgen -l pets-mouses -d 'Generate Pets Mouses style names'
complete -c namgen -l pets-owls -d 'Generate Pets Owls style names'
complete -c namgen -l pets-parrots -d 'Generate Pets Parrots style names'
complete -c namgen -l pets-pigs -d 'Generate Pets Pigs style names'
complete -c namgen -l pets-rabbits -d 'Generate Pets Rabbits style names'
complete -c namgen -l pets-reptiles -d 'Generate Pets Reptiles style names'
complete -c namgen -l pets-rodents -d 'Generate Pets Rodents style names'
complete -c namgen -l pets-sheeps -d 'Generate Pets Sheeps style names'
complete -c namgen -l pets-turtles -d 'Generate Pets Turtles style names'
complete -c namgen -l pets-wolfs -d 'Generate Pets Wolfs style names'
complete -c namgen -l places-amusement_parks -d 'Generate Places Amusement Parks style names'
complete -c namgen -l places-antique_stores -d 'Generate Places Antique Stores style names'
complete -c namgen -l places-asylums -d 'Generate Places Asylums style names'
complete -c namgen -l places-bakerys -d 'Generate Places Bakerys style names'
complete -c namgen -l places-banks -d 'Generate Places Banks style names'
complete -c namgen -l places-battle_arenas -d 'Generate Places Battle Arenas style names'
complete -c namgen -l places-beachs -d 'Generate Places Beachs style names'
complete -c namgen -l places-brewerys -d 'Generate Places Brewerys style names'
complete -c namgen -l places-bridges -d 'Generate Places Bridges style names'
complete -c namgen -l places-business -d 'Generate Places Business style names'
complete -c namgen -l places-cafes -d 'Generate Places Cafes style names'
complete -c namgen -l places-camps -d 'Generate Places Camps style names'
complete -c namgen -l places-casinos -d 'Generate Places Casinos style names'
complete -c namgen -l places-castles -d 'Generate Places Castles style names'
complete -c namgen -l places-caves -d 'Generate Places Caves style names'
complete -c namgen -l places-circus -d 'Generate Places Circus style names'
complete -c namgen -l places-city_districts -d 'Generate Places City Districts style names'
complete -c namgen -l places-civilizations -d 'Generate Places Civilizations style names'
complete -c namgen -l places-cliffs -d 'Generate Places Cliffs style names'
complete -c namgen -l places-companys -d 'Generate Places Companys style names'
complete -c namgen -l places-continents -d 'Generate Places Continents style names'
complete -c namgen -l places-countrys -d 'Generate Places Countrys style names'
complete -c namgen -l places-day_cares -d 'Generate Places Day Cares style names'
complete -c namgen -l places-dimensions -d 'Generate Places Dimensions style names'
complete -c namgen -l places-dungeons -d 'Generate Places Dungeons style names'
complete -c namgen -l places-farms -d 'Generate Places Farms style names'
complete -c namgen -l places-film_studios -d 'Generate Places Film Studios style names'
complete -c namgen -l places-fire_lands -d 'Generate Places Fire Lands style names'
complete -c namgen -l places-forests -d 'Generate Places Forests style names'
complete -c namgen -l places-game_studios -d 'Generate Places Game Studios style names'
complete -c namgen -l places-grasslands -d 'Generate Places Grasslands style names'
complete -c namgen -l places-graveyards -d 'Generate Places Graveyards style names'
complete -c namgen -l places-harbors -d 'Generate Places Harbors style names'
complete -c namgen -l places-headquarters -d 'Generate Places Headquarters style names'
complete -c namgen -l places-hospitals -d 'Generate Places Hospitals style names'
complete -c namgen -l places-hotels -d 'Generate Places Hotels style names'
complete -c namgen -l places-inns -d 'Generate Places Inns style names'
complete -c namgen -l places-islands -d 'Generate Places Islands style names'
complete -c namgen -l places-jungles -d 'Generate Places Jungles style names'
complete -c namgen -l places-kingdoms -d 'Generate Places Kingdoms style names'
complete -c namgen -l places-laboratorys -d 'Generate Places Laboratorys style names'
complete -c namgen -l places-lakes -d 'Generate Places Lakes style names'
complete -c namgen -l places-lands -d 'Generate Places Lands style names'
complete -c namgen -l places-librarys -d 'Generate Places Librarys style names'
complete -c namgen -l places-magic_schools -d 'Generate Places Magic Schools style names'
complete -c namgen -l places-magic_shops -d 'Generate Places Magic Shops style names'
complete -c namgen -l places-mansions -d 'Generate Places Mansions style names'
complete -c namgen -l places-mining_companys -d 'Generate Places Mining Companys style names'
complete -c namgen -l places-mountains -d 'Generate Places Mountains style names'
complete -c namgen -l places-museums -d 'Generate Places Museums style names'
complete -c namgen -l places-nightclubs -d 'Generate Places Nightclubs style names'
complete -c namgen -l places-oasis -d 'Generate Places Oasis style names'
complete -c namgen -l places-orphanages -d 'Generate Places Orphanages style names'
complete -c namgen -l places-outposts -d 'Generate Places Outposts style names'
complete -c namgen -l places-parks -d 'Generate Places Parks style names'
complete -c namgen -l places-pirate_coves -d 'Generate Places Pirate Coves style names'
complete -c namgen -l places-planets -d 'Generate Places Planets style names'
complete -c namgen -l places-plantations -d 'Generate Places Plantations style names'
complete -c namgen -l places-plazas -d 'Generate Places Plazas style names'
complete -c namgen -l places-prisons -d 'Generate Places Prisons style names'
complete -c namgen -l places-realms -d 'Generate Places Realms style names'
complete -c namgen -l places-restaurants -d 'Generate Places Restaurants style names'
complete -c namgen -l places-rivers -d 'Generate Places Rivers style names'
complete -c namgen -l places-roads -d 'Generate Places Roads style names'
complete -c namgen -l places-ruins -d 'Generate Places Ruins style names'
complete -c namgen -l places-schools -d 'Generate Places Schools style names'
complete -c namgen -l places-shops -d 'Generate Places Shops style names'
complete -c namgen -l places-sky_islands -d 'Generate Places Sky Islands style names'
complete -c namgen -l places-snowlands -d 'Generate Places Snowlands style names'
complete -c namgen -l places-space_colonys -d 'Generate Places Space Colonys style names'
complete -c namgen -l places-stadiums -d 'Generate Places Stadiums style names'
complete -c namgen -l places-stars -d 'Generate Places Stars style names'
complete -c namgen -l places-streets -d 'Generate Places Streets style names'
complete -c namgen -l places-swamps -d 'Generate Places Swamps style names'
complete -c namgen -l places-temples -d 'Generate Places Temples style names'
complete -c namgen -l places-theaters -d 'Generate Places Theaters style names'
complete -c namgen -l places-towers -d 'Generate Places Towers style names'
complete -c namgen -l places-volcanos -d 'Generate Places Volcanos style names'
complete -c namgen -l places-waterfalls -d 'Generate Places Waterfalls style names'
complete -c namgen -l places-waters -d 'Generate Places Waters style names'
complete -c namgen -l pop_culture-arthurians -d 'Generate Pop Culture Arthurians style names'
complete -c namgen -l pop_culture-avatar_last_airbenders -d 'Generate Pop Culture Avatar Last Airbenders style names'
complete -c namgen -l pop_culture-digimons -d 'Generate Pop Culture Digimons style names'
complete -c namgen -l pop_culture-dragonriders_of_perns -d 'Generate Pop Culture Dragonriders Of Perns style names'
complete -c namgen -l pop_culture-homestucks -d 'Generate Pop Culture Homestucks style names'
complete -c namgen -l pop_culture-how_to_train_your_dragons -d 'Generate Pop Culture How To Train Your Dragons style names'
complete -c namgen -l pop_culture-hunger_games -d 'Generate Pop Culture Hunger Games style names'
complete -c namgen -l pop_culture-hyborians -d 'Generate Pop Culture Hyborians style names'
complete -c namgen -l pop_culture-lovecraftians -d 'Generate Pop Culture Lovecraftians style names'
complete -c namgen -l pop_culture-maze_runners -d 'Generate Pop Culture Maze Runners style names'
complete -c namgen -l pop_culture-mortal_kombats -d 'Generate Pop Culture Mortal Kombats style names'
complete -c namgen -l pop_culture-my_little_ponys -d 'Generate Pop Culture My Little Ponys style names'
complete -c namgen -l pop_culture-one_piece_devil_fruits -d 'Generate Pop Culture One Piece Devil Fruits style names'
complete -c namgen -l pop_culture-pacific_rims -d 'Generate Pop Culture Pacific Rims style names'
complete -c namgen -l pop_culture-pokemons -d 'Generate Pop Culture Pokemons style names'
complete -c namgen -l pop_culture-rwbys -d 'Generate Pop Culture Rwbys style names'
complete -c namgen -l pop_culture-shadowhunter_chronicles -d 'Generate Pop Culture Shadowhunter Chronicles style names'
complete -c namgen -l pop_culture-skulduggery_pleasants -d 'Generate Pop Culture Skulduggery Pleasants style names'
complete -c namgen -l pop_culture-starcrafts -d 'Generate Pop Culture Starcrafts style names'
complete -c namgen -l pop_culture-stormlight_archives -d 'Generate Pop Culture Stormlight Archives style names'
complete -c namgen -l pop_culture-transformers -d 'Generate Pop Culture Transformers style names'
complete -c namgen -l pop_culture-warrior_cats -d 'Generate Pop Culture Warrior Cats style names'
complete -c namgen -l pop_culture-wheel_of_times -d 'Generate Pop Culture Wheel Of Times style names'
complete -c namgen -l pop_culture-wings_of_fires -d 'Generate Pop Culture Wings Of Fires style names'
complete -c namgen -l pop_culture-x_mens -d 'Generate Pop Culture X Mens style names'
complete -c namgen -l real-20th_century_englishs -d 'Generate Real 20Th Century Englishs style names'
complete -c namgen -l real-aboriginals -d 'Generate Real Aboriginals style names'
complete -c namgen -l real-african_americans -d 'Generate Real African Americans style names'
complete -c namgen -l real-akans -d 'Generate Real Akans style names'
complete -c namgen -l real-albanians -d 'Generate Real Albanians style names'
complete -c namgen -l real-algerians -d 'Generate Real Algerians style names'
complete -c namgen -l real-amazighs -d 'Generate Real Amazighs style names'
complete -c namgen -l real-ancient_greeks -d 'Generate Real Ancient Greeks style names'
complete -c namgen -l real-anglo_saxons -d 'Generate Real Anglo Saxons style names'
complete -c namgen -l real-argentinians -d 'Generate Real Argentinians style names'
complete -c namgen -l real-armenians -d 'Generate Real Armenians style names'
complete -c namgen -l real-assyrians -d 'Generate Real Assyrians style names'
complete -c namgen -l real-azerbaijanis -d 'Generate Real Azerbaijanis style names'
complete -c namgen -l real-aztecs -d 'Generate Real Aztecs style names'
complete -c namgen -l real-babylonians -d 'Generate Real Babylonians style names'
complete -c namgen -l real-basothos -d 'Generate Real Basothos style names'
complete -c namgen -l real-basques -d 'Generate Real Basques style names'
complete -c namgen -l real-belgians -d 'Generate Real Belgians style names'
complete -c namgen -l real-bengalis -d 'Generate Real Bengalis style names'
complete -c namgen -l real-biblicals -d 'Generate Real Biblicals style names'
complete -c namgen -l real-bosnians -d 'Generate Real Bosnians style names'
complete -c namgen -l real-brazilians -d 'Generate Real Brazilians style names'
complete -c namgen -l real-bulgarians -d 'Generate Real Bulgarians style names'
complete -c namgen -l real-burmese_myanmars -d 'Generate Real Burmese Myanmars style names'
complete -c namgen -l real-cajuns -d 'Generate Real Cajuns style names'
complete -c namgen -l real-catalans -d 'Generate Real Catalans style names'
complete -c namgen -l real-celtic_bretons -d 'Generate Real Celtic Bretons style names'
complete -c namgen -l real-celtic_welshs -d 'Generate Real Celtic Welshs style names'
complete -c namgen -l real-celtics -d 'Generate Real Celtics style names'
complete -c namgen -l real-chineses -d 'Generate Real Chineses style names'
complete -c namgen -l real-circassians -d 'Generate Real Circassians style names'
complete -c namgen -l real-colonial_americans -d 'Generate Real Colonial Americans style names'
complete -c namgen -l real-croatians -d 'Generate Real Croatians style names'
complete -c namgen -l real-czechs -d 'Generate Real Czechs style names'
complete -c namgen -l real-danishs -d 'Generate Real Danishs style names'
complete -c namgen -l real-dutchs -d 'Generate Real Dutchs style names'
complete -c namgen -l real-edo_japaneses -d 'Generate Real Edo Japaneses style names'
complete -c namgen -l real-edwardians -d 'Generate Real Edwardians style names'
complete -c namgen -l real-egyptians -d 'Generate Real Egyptians style names'
complete -c namgen -l real-englishs -d 'Generate Real Englishs style names'
complete -c namgen -l real-enochians -d 'Generate Real Enochians style names'
complete -c namgen -l real-estonians -d 'Generate Real Estonians style names'
complete -c namgen -l real-ethiopians -d 'Generate Real Ethiopians style names'
complete -c namgen -l real-faroeses -d 'Generate Real Faroeses style names'
complete -c namgen -l real-filipinos -d 'Generate Real Filipinos style names'
complete -c namgen -l real-finnishs -d 'Generate Real Finnishs style names'
complete -c namgen -l real-frankishs -d 'Generate Real Frankishs style names'
complete -c namgen -l real-frenchs -d 'Generate Real Frenchs style names'
complete -c namgen -l real-frisians -d 'Generate Real Frisians style names'
complete -c namgen -l real-georgians -d 'Generate Real Georgians style names'
complete -c namgen -l real-germans -d 'Generate Real Germans style names'
complete -c namgen -l real-gothics -d 'Generate Real Gothics style names'
complete -c namgen -l real-greeks -d 'Generate Real Greeks style names'
complete -c namgen -l real-hausas -d 'Generate Real Hausas style names'
complete -c namgen -l real-hawaiians -d 'Generate Real Hawaiians style names'
complete -c namgen -l real-hebrews -d 'Generate Real Hebrews style names'
complete -c namgen -l real-hillbillys -d 'Generate Real Hillbillys style names'
complete -c namgen -l real-hindus -d 'Generate Real Hindus style names'
complete -c namgen -l real-hippies -d 'Generate Real Hippies style names'
complete -c namgen -l real-hispanics -d 'Generate Real Hispanics style names'
complete -c namgen -l real-hungarians -d 'Generate Real Hungarians style names'
complete -c namgen -l real-icelandics -d 'Generate Real Icelandics style names'
complete -c namgen -l real-indonesians -d 'Generate Real Indonesians style names'
complete -c namgen -l real-inuits -d 'Generate Real Inuits style names'
complete -c namgen -l real-irishs -d 'Generate Real Irishs style names'
complete -c namgen -l real-italians -d 'Generate Real Italians style names'
complete -c namgen -l real-jamaicans -d 'Generate Real Jamaicans style names'
complete -c namgen -l real-japaneses -d 'Generate Real Japaneses style names'
complete -c namgen -l real-jewishs -d 'Generate Real Jewishs style names'
complete -c namgen -l real-kazakhs -d 'Generate Real Kazakhs style names'
complete -c namgen -l real-khmers -d 'Generate Real Khmers style names'
complete -c namgen -l real-koreans -d 'Generate Real Koreans style names'
complete -c namgen -l real-kurdishs -d 'Generate Real Kurdishs style names'
complete -c namgen -l real-laotians -d 'Generate Real Laotians style names'
complete -c namgen -l real-latins -d 'Generate Real Latins style names'
complete -c namgen -l real-latvians -d 'Generate Real Latvians style names'
complete -c namgen -l real-lithuanians -d 'Generate Real Lithuanians style names'
complete -c namgen -l real-malaysians -d 'Generate Real Malaysians style names'
complete -c namgen -l real-malteses -d 'Generate Real Malteses style names'
complete -c namgen -l real-maoris -d 'Generate Real Maoris style names'
complete -c namgen -l real-mayans -d 'Generate Real Mayans style names'
complete -c namgen -l real-modern_egyptians -d 'Generate Real Modern Egyptians style names'
complete -c namgen -l real-mongolians -d 'Generate Real Mongolians style names'
complete -c namgen -l real-moroccans -d 'Generate Real Moroccans style names'
complete -c namgen -l real-muslims -d 'Generate Real Muslims style names'
complete -c namgen -l real-native_americans -d 'Generate Real Native Americans style names'
complete -c namgen -l real-natures -d 'Generate Real Natures style names'
complete -c namgen -l real-nepaleses -d 'Generate Real Nepaleses style names'
complete -c namgen -l real-normans -d 'Generate Real Normans style names'
complete -c namgen -l real-norwegians -d 'Generate Real Norwegians style names'
complete -c namgen -l real-old_high_germans -d 'Generate Real Old High Germans style names'
complete -c namgen -l real-pashtuns -d 'Generate Real Pashtuns style names'
complete -c namgen -l real-persians -d 'Generate Real Persians style names'
complete -c namgen -l real-polishs -d 'Generate Real Polishs style names'
complete -c namgen -l real-portugueses -d 'Generate Real Portugueses style names'
complete -c namgen -l real-poshs -d 'Generate Real Poshs style names'
complete -c namgen -l real-punjabis -d 'Generate Real Punjabis style names'
complete -c namgen -l real-puritans -d 'Generate Real Puritans style names'
complete -c namgen -l real-quebecois -d 'Generate Real Quebecois style names'
complete -c namgen -l real-roma_gypsys -d 'Generate Real Roma Gypsys style names'
complete -c namgen -l real-romanians -d 'Generate Real Romanians style names'
complete -c namgen -l real-romans -d 'Generate Real Romans style names'
complete -c namgen -l real-russians -d 'Generate Real Russians style names'
complete -c namgen -l real-serbians -d 'Generate Real Serbians style names'
complete -c namgen -l real-shakespeareans -d 'Generate Real Shakespeareans style names'
complete -c namgen -l real-shonas -d 'Generate Real Shonas style names'
complete -c namgen -l real-sikhs -d 'Generate Real Sikhs style names'
complete -c namgen -l real-sinhaleses -d 'Generate Real Sinhaleses style names'
complete -c namgen -l real-slavics -d 'Generate Real Slavics style names'
complete -c namgen -l real-slovenians -d 'Generate Real Slovenians style names'
complete -c namgen -l real-somalis -d 'Generate Real Somalis style names'
complete -c namgen -l real-stages -d 'Generate Real Stages style names'
complete -c namgen -l real-suebis -d 'Generate Real Suebis style names'
complete -c namgen -l real-sumerians -d 'Generate Real Sumerians style names'
complete -c namgen -l real-swahilis -d 'Generate Real Swahilis style names'
complete -c namgen -l real-swedishs -d 'Generate Real Swedishs style names'
complete -c namgen -l real-swiss -d 'Generate Real Swiss style names'
complete -c namgen -l real-tajiks -d 'Generate Real Tajiks style names'
complete -c namgen -l real-tamils -d 'Generate Real Tamils style names'
complete -c namgen -l real-telugus -d 'Generate Real Telugus style names'
complete -c namgen -l real-thais -d 'Generate Real Thais style names'
complete -c namgen -l real-tibetans -d 'Generate Real Tibetans style names'
complete -c namgen -l real-turkishs -d 'Generate Real Turkishs style names'
complete -c namgen -l real-twins -d 'Generate Real Twins style names'
complete -c namgen -l real-ukrainians -d 'Generate Real Ukrainians style names'
complete -c namgen -l real-victorians -d 'Generate Real Victorians style names'
complete -c namgen -l real-vietnameses -d 'Generate Real Vietnameses style names'
complete -c namgen -l real-vikings -d 'Generate Real Vikings style names'
complete -c namgen -l real-yorubas -d 'Generate Real Yorubas style names'
complete -c namgen -l real-zulus -d 'Generate Real Zulus style names'
complete -c namgen -l rift-bahmis -d 'Generate Rift Bahmis style names'
complete -c namgen -l rift-dwarfs -d 'Generate Rift Dwarfs style names'
complete -c namgen -l rift-eths -d 'Generate Rift Eths style names'
complete -c namgen -l rift-high_elfs -d 'Generate Rift High Elfs style names'
complete -c namgen -l rift-kelaris -d 'Generate Rift Kelaris style names'
complete -c namgen -l rift-mathosians -d 'Generate Rift Mathosians style names'
complete -c namgen -l star_trek-andorians -d 'Generate Star Trek Andorians style names'
complete -c namgen -l star_trek-bajorans -d 'Generate Star Trek Bajorans style names'
complete -c namgen -l star_trek-benzites -d 'Generate Star Trek Benzites style names'
complete -c namgen -l star_trek-betazoids -d 'Generate Star Trek Betazoids style names'
complete -c namgen -l star_trek-bolians -d 'Generate Star Trek Bolians style names'
complete -c namgen -l star_trek-caitians -d 'Generate Star Trek Caitians style names'
complete -c namgen -l star_trek-ferengis -d 'Generate Star Trek Ferengis style names'
complete -c namgen -l star_trek-gorns -d 'Generate Star Trek Gorns style names'
complete -c namgen -l star_trek-jemhadars -d 'Generate Star Trek Jemhadars style names'
complete -c namgen -l star_trek-klingons -d 'Generate Star Trek Klingons style names'
complete -c namgen -l star_trek-letheans -d 'Generate Star Trek Letheans style names'
complete -c namgen -l star_trek-nausicaans -d 'Generate Star Trek Nausicaans style names'
complete -c namgen -l star_trek-orions -d 'Generate Star Trek Orions style names'
complete -c namgen -l star_trek-pakleds -d 'Generate Star Trek Pakleds style names'
complete -c namgen -l star_trek-remans -d 'Generate Star Trek Remans style names'
complete -c namgen -l star_trek-rigelians -d 'Generate Star Trek Rigelians style names'
complete -c namgen -l star_trek-romulans -d 'Generate Star Trek Romulans style names'
complete -c namgen -l star_trek-saurians -d 'Generate Star Trek Saurians style names'
complete -c namgen -l star_trek-tellarites -d 'Generate Star Trek Tellarites style names'
complete -c namgen -l star_trek-trills -d 'Generate Star Trek Trills style names'
complete -c namgen -l star_trek-vulcans -d 'Generate Star Trek Vulcans style names'
complete -c namgen -l star_wars-anzatis -d 'Generate Star Wars Anzatis style names'
complete -c namgen -l star_wars-biths -d 'Generate Star Wars Biths style names'
complete -c namgen -l star_wars-bothans -d 'Generate Star Wars Bothans style names'
complete -c namgen -l star_wars-darths -d 'Generate Star Wars Darths style names'
complete -c namgen -l star_wars-devaronians -d 'Generate Star Wars Devaronians style names'
complete -c namgen -l star_wars-dugs -d 'Generate Star Wars Dugs style names'
complete -c namgen -l star_wars-duross -d 'Generate Star Wars Duross style names'
complete -c namgen -l star_wars-ewoks -d 'Generate Star Wars Ewoks style names'
complete -c namgen -l star_wars-falleens -d 'Generate Star Wars Falleens style names'
complete -c namgen -l star_wars-gamorreans -d 'Generate Star Wars Gamorreans style names'
complete -c namgen -l star_wars-gands -d 'Generate Star Wars Gands style names'
complete -c namgen -l star_wars-gotals -d 'Generate Star Wars Gotals style names'
complete -c namgen -l star_wars-grans -d 'Generate Star Wars Grans style names'
complete -c namgen -l star_wars-gungans -d 'Generate Star Wars Gungans style names'
complete -c namgen -l star_wars-hutts -d 'Generate Star Wars Hutts style names'
complete -c namgen -l star_wars-iktotchis -d 'Generate Star Wars Iktotchis style names'
complete -c namgen -l star_wars-ishi_tibs -d 'Generate Star Wars Ishi Tibs style names'
complete -c namgen -l star_wars-ithorians -d 'Generate Star Wars Ithorians style names'
complete -c namgen -l star_wars-jawas -d 'Generate Star Wars Jawas style names'
complete -c namgen -l star_wars-kel_dors -d 'Generate Star Wars Kel Dors style names'
complete -c namgen -l star_wars-korunnais -d 'Generate Star Wars Korunnais style names'
complete -c namgen -l star_wars-mandalorians -d 'Generate Star Wars Mandalorians style names'
complete -c namgen -l star_wars-mon_calamaris -d 'Generate Star Wars Mon Calamaris style names'
complete -c namgen -l star_wars-nautolans -d 'Generate Star Wars Nautolans style names'
complete -c namgen -l star_wars-neimoidians -d 'Generate Star Wars Neimoidians style names'
complete -c namgen -l star_wars-niktos -d 'Generate Star Wars Niktos style names'
complete -c namgen -l star_wars-ortolans -d 'Generate Star Wars Ortolans style names'
complete -c namgen -l star_wars-quarrens -d 'Generate Star Wars Quarrens style names'
complete -c namgen -l star_wars-rodians -d 'Generate Star Wars Rodians style names'
complete -c namgen -l star_wars-shistavanens -d 'Generate Star Wars Shistavanens style names'
complete -c namgen -l star_wars-sullustans -d 'Generate Star Wars Sullustans style names'
complete -c namgen -l star_wars-swiss -d 'Generate Star Wars Swiss style names'
complete -c namgen -l star_wars-toydarians -d 'Generate Star Wars Toydarians style names'
complete -c namgen -l star_wars-trandoshans -d 'Generate Star Wars Trandoshans style names'
complete -c namgen -l star_wars-tusken_raiders -d 'Generate Star Wars Tusken Raiders style names'
complete -c namgen -l star_wars-weequays -d 'Generate Star Wars Weequays style names'
complete -c namgen -l star_wars-wookiees -d 'Generate Star Wars Wookiees style names'
complete -c namgen -l star_wars_the_old_republic-cathars -d 'Generate Star Wars The Old Republic Cathars style names'
complete -c namgen -l star_wars_the_old_republic-chiss -d 'Generate Star Wars The Old Republic Chiss style names'
complete -c namgen -l star_wars_the_old_republic-cyborgs -d 'Generate Star Wars The Old Republic Cyborgs style names'
complete -c namgen -l star_wars_the_old_republic-human_sws -d 'Generate Star Wars The Old Republic Human Sws style names'
complete -c namgen -l star_wars_the_old_republic-miralukas -d 'Generate Star Wars The Old Republic Miralukas style names'
complete -c namgen -l star_wars_the_old_republic-mirialans -d 'Generate Star Wars The Old Republic Mirialans style names'
complete -c namgen -l star_wars_the_old_republic-rattatakis -d 'Generate Star Wars The Old Republic Rattatakis style names'
complete -c namgen -l star_wars_the_old_republic-siths -d 'Generate Star Wars The Old Republic Siths style names'
complete -c namgen -l star_wars_the_old_republic-togrutas -d 'Generate Star Wars The Old Republic Togrutas style names'
complete -c namgen -l star_wars_the_old_republic-twileks -d 'Generate Star Wars The Old Republic Twileks style names'
complete -c namgen -l star_wars_the_old_republic-zabraks -d 'Generate Star Wars The Old Republic Zabraks style names'
complete -c namgen -l the_witcher-dwarfs -d 'Generate The Witcher Dwarfs style names'
complete -c namgen -l the_witcher-elfs -d 'Generate The Witcher Elfs style names'
complete -c namgen -l the_witcher-halflings -d 'Generate The Witcher Halflings style names'
complete -c namgen -l the_witcher-humans -d 'Generate The Witcher Humans style names'
complete -c namgen -l towns_and_cities-ancient_greek_towns -d 'Generate Towns And Cities Ancient Greek Towns style names'
complete -c namgen -l towns_and_cities-apocalypse_towns -d 'Generate Towns And Cities Apocalypse Towns style names'
complete -c namgen -l towns_and_cities-central_african_towns -d 'Generate Towns And Cities Central African Towns style names'
complete -c namgen -l towns_and_cities-central_american_towns -d 'Generate Towns And Cities Central American Towns style names'
complete -c namgen -l towns_and_cities-central_east_african_towns -d 'Generate Towns And Cities Central East African Towns style names'
complete -c namgen -l towns_and_cities-city_nicknames -d 'Generate Towns And Cities City Nicknames style names'
complete -c namgen -l towns_and_cities-citys -d 'Generate Towns And Cities Citys style names'
complete -c namgen -l towns_and_cities-dwarven_citys -d 'Generate Towns And Cities Dwarven Citys style names'
complete -c namgen -l towns_and_cities-east_asian_towns -d 'Generate Towns And Cities East Asian Towns style names'
complete -c namgen -l towns_and_cities-east_european_towns -d 'Generate Towns And Cities East European Towns style names'
complete -c namgen -l towns_and_cities-egyptian_towns -d 'Generate Towns And Cities Egyptian Towns style names'
complete -c namgen -l towns_and_cities-elven_citys -d 'Generate Towns And Cities Elven Citys style names'
complete -c namgen -l towns_and_cities-fantasy_towns -d 'Generate Towns And Cities Fantasy Towns style names'
complete -c namgen -l towns_and_cities-middle_eastern_towns -d 'Generate Towns And Cities Middle Eastern Towns style names'
complete -c namgen -l towns_and_cities-north_african_towns -d 'Generate Towns And Cities North African Towns style names'
complete -c namgen -l towns_and_cities-north_american_towns -d 'Generate Towns And Cities North American Towns style names'
complete -c namgen -l towns_and_cities-north_european_towns -d 'Generate Towns And Cities North European Towns style names'
complete -c namgen -l towns_and_cities-northern_south_american_towns -d 'Generate Towns And Cities Northern South American Towns style names'
complete -c namgen -l towns_and_cities-oceania_towns -d 'Generate Towns And Cities Oceania Towns style names'
complete -c namgen -l towns_and_cities-orcish_citys -d 'Generate Towns And Cities Orcish Citys style names'
complete -c namgen -l towns_and_cities-roman_towns -d 'Generate Towns And Cities Roman Towns style names'
complete -c namgen -l towns_and_cities-russian_towns -d 'Generate Towns And Cities Russian Towns style names'
complete -c namgen -l towns_and_cities-south_african_towns -d 'Generate Towns And Cities South African Towns style names'
complete -c namgen -l towns_and_cities-south_american_towns -d 'Generate Towns And Cities South American Towns style names'
complete -c namgen -l towns_and_cities-south_asian_towns -d 'Generate Towns And Cities South Asian Towns style names'
complete -c namgen -l towns_and_cities-south_european_towns -d 'Generate Towns And Cities South European Towns style names'
complete -c namgen -l towns_and_cities-southeast_african_towns -d 'Generate Towns And Cities Southeast African Towns style names'
complete -c namgen -l towns_and_cities-southeast_asian_towns -d 'Generate Towns And Cities Southeast Asian Towns style names'
complete -c namgen -l towns_and_cities-southeast_european -d 'Generate Towns And Cities Southeast European style names'
complete -c namgen -l towns_and_cities-steampunk_citys -d 'Generate Towns And Cities Steampunk Citys style names'
complete -c namgen -l towns_and_cities-towns -d 'Generate Towns And Cities Towns style names'
complete -c namgen -l towns_and_cities-underwater_citys -d 'Generate Towns And Cities Underwater Citys style names'
complete -c namgen -l towns_and_cities-viking_towns -d 'Generate Towns And Cities Viking Towns style names'
complete -c namgen -l towns_and_cities-west_african_towns -d 'Generate Towns And Cities West African Towns style names'
complete -c namgen -l towns_and_cities-west_european_towns -d 'Generate Towns And Cities West European Towns style names'
complete -c namgen -l towns_and_cities-wild_west_towns -d 'Generate Towns And Cities Wild West Towns style names'
complete -c namgen -l warhammer-beastmens -d 'Generate Warhammer Beastmens style names'
complete -c namgen -l warhammer-bretonnias -d 'Generate Warhammer Bretonnias style names'
complete -c namgen -l warhammer-daemons_of_chaos -d 'Generate Warhammer Daemons Of Chaos style names'
complete -c namgen -l warhammer-dark_elfs -d 'Generate Warhammer Dark Elfs style names'
complete -c namgen -l warhammer-dwarfs -d 'Generate Warhammer Dwarfs style names'
complete -c namgen -l warhammer-empires -d 'Generate Warhammer Empires style names'
complete -c namgen -l warhammer-goblins -d 'Generate Warhammer Goblins style names'
complete -c namgen -l warhammer-high_elfs -d 'Generate Warhammer High Elfs style names'
complete -c namgen -l warhammer-lizardmens -d 'Generate Warhammer Lizardmens style names'
complete -c namgen -l warhammer-ogres -d 'Generate Warhammer Ogres style names'
complete -c namgen -l warhammer-orcs -d 'Generate Warhammer Orcs style names'
complete -c namgen -l warhammer-skavens -d 'Generate Warhammer Skavens style names'
complete -c namgen -l warhammer-tomb_kings -d 'Generate Warhammer Tomb Kings style names'
complete -c namgen -l warhammer-vampire_counts -d 'Generate Warhammer Vampire Counts style names'
complete -c namgen -l warhammer-warriors_of_chaos -d 'Generate Warhammer Warriors Of Chaos style names'
complete -c namgen -l warhammer-wood_elfs -d 'Generate Warhammer Wood Elfs style names'
complete -c namgen -l warhammer_40k-chaos -d 'Generate Warhammer 40K Chaos style names'
complete -c namgen -l warhammer_40k-dark_eldars -d 'Generate Warhammer 40K Dark Eldars style names'
complete -c namgen -l warhammer_40k-eldars -d 'Generate Warhammer 40K Eldars style names'
complete -c namgen -l warhammer_40k-necrons -d 'Generate Warhammer 40K Necrons style names'
complete -c namgen -l warhammer_40k-orks -d 'Generate Warhammer 40K Orks style names'
complete -c namgen -l warhammer_40k-sisters_of_battles -d 'Generate Warhammer 40K Sisters Of Battles style names'
complete -c namgen -l warhammer_40k-space_marines -d 'Generate Warhammer 40K Space Marines style names'
complete -c namgen -l warhammer_40k-taus -d 'Generate Warhammer 40K Taus style names'
complete -c namgen -l weapons-battle_axes -d 'Generate Weapons Battle Axes style names'
complete -c namgen -l weapons-bomb_missiles -d 'Generate Weapons Bomb Missiles style names'
complete -c namgen -l weapons-bows -d 'Generate Weapons Bows style names'
complete -c namgen -l weapons-claw_weapons -d 'Generate Claw Weapons style names'
complete -c namgen -l weapons-daggers -d 'Generate Weapons Daggers style names'
complete -c namgen -l weapons-dual_wields -d 'Generate Weapons Dual Wields style names'
complete -c namgen -l weapons-fist_weapons -d 'Generate Fist Weapons style names'
complete -c namgen -l weapons-flails -d 'Generate Weapons Flails style names'
complete -c namgen -l weapons-magic_books -d 'Generate Weapons Magic Books style names'
complete -c namgen -l weapons-magic_weapons -d 'Generate Magic Weapons style names'
complete -c namgen -l weapons-pistols -d 'Generate Weapons Pistols style names'
complete -c namgen -l weapons-rifles -d 'Generate Weapons Rifles style names'
complete -c namgen -l weapons-sci_fi_guns -d 'Generate Weapons Sci Fi Guns style names'
complete -c namgen -l weapons-scythes -d 'Generate Weapons Scythes style names'
complete -c namgen -l weapons-shotguns -d 'Generate Weapons Shotguns style names'
complete -c namgen -l weapons-spears -d 'Generate Weapons Spears style names'
complete -c namgen -l weapons-staffs -d 'Generate Weapons Staffs style names'
complete -c namgen -l weapons-swords -d 'Generate Weapons Swords style names'
complete -c namgen -l weapons-throwing_weapons -d 'Generate Throwing Weapons style names'
complete -c namgen -l weapons-war_hammers -d 'Generate Weapons War Hammers style names'
complete -c namgen -l weapons-whips -d 'Generate Weapons Whips style names'
complete -c namgen -l wildstar-aurins -d 'Generate Wildstar Aurins style names'
complete -c namgen -l wildstar-cassians -d 'Generate Wildstar Cassians style names'
complete -c namgen -l wildstar-chuas -d 'Generate Wildstar Chuas style names'
complete -c namgen -l wildstar-drakens -d 'Generate Wildstar Drakens style names'
complete -c namgen -l wildstar-granoks -d 'Generate Wildstar Granoks style names'
complete -c namgen -l wildstar-humans -d 'Generate Wildstar Humans style names'
complete -c namgen -l wildstar-mecharis -d 'Generate Wildstar Mecharis style names'
complete -c namgen -l wildstar-mordeshs -d 'Generate Wildstar Mordeshs style names'
complete -c namgen -l world_of_warcraft-blood_elf -d 'Generate World Of Warcraft Blood Elf style names'
complete -c namgen -l world_of_warcraft-draenei -d 'Generate World Of Warcraft Draenei style names'
complete -c namgen -l world_of_warcraft-dwarf -d 'Generate World Of Warcraft Dwarf style names'
complete -c namgen -l world_of_warcraft-forsaken -d 'Generate World Of Warcraft Forsaken style names'
complete -c namgen -l world_of_warcraft-gnome -d 'Generate World Of Warcraft Gnome style names'
complete -c namgen -l world_of_warcraft-goblin -d 'Generate World Of Warcraft Goblin style names'
complete -c namgen -l world_of_warcraft-human -d 'Generate World Of Warcraft Human style names'
complete -c namgen -l world_of_warcraft-night_elf -d 'Generate World Of Warcraft Night Elf style names'
complete -c namgen -l world_of_warcraft-orc -d 'Generate World Of Warcraft Orc style names'
complete -c namgen -l world_of_warcraft-pandaren -d 'Generate World Of Warcraft Pandaren style names'
complete -c namgen -l world_of_warcraft-tauren -d 'Generate World Of Warcraft Tauren style names'
complete -c namgen -l world_of_warcraft-troll -d 'Generate World Of Warcraft Troll style names'
complete -c namgen -l world_of_warcraft-worgen -d 'Generate World Of Warcraft Worgen style names'
complete -c namgen -l world_of_warcraft_pets-bat_dragonhawks -d 'Generate World Of Warcraft Pets Bat Dragonhawks style names'
complete -c namgen -l world_of_warcraft_pets-birds -d 'Generate World Of Warcraft Pets Birds style names'
complete -c namgen -l world_of_warcraft_pets-boars_bears -d 'Generate World Of Warcraft Pets Boars Bears style names'
complete -c namgen -l world_of_warcraft_pets-cats -d 'Generate World Of Warcraft Pets Cats style names'
complete -c namgen -l world_of_warcraft_pets-crabs -d 'Generate World Of Warcraft Pets Crabs style names'
complete -c namgen -l world_of_warcraft_pets-dino_rhinos -d 'Generate World Of Warcraft Pets Dino Rhinos style names'
complete -c namgen -l world_of_warcraft_pets-dog_wolfs -d 'Generate World Of Warcraft Pets Dog Wolfs style names'
complete -c namgen -l world_of_warcraft_pets-goat_porcupines -d 'Generate World Of Warcraft Pets Goat Porcupines style names'
complete -c namgen -l world_of_warcraft_pets-gorilla_monkeys -d 'Generate World Of Warcraft Pets Gorilla Monkeys style names'
complete -c namgen -l world_of_warcraft_pets-insects -d 'Generate World Of Warcraft Pets Insects style names'
complete -c namgen -l world_of_warcraft_pets-reptiles -d 'Generate World Of Warcraft Pets Reptiles style names'
complete -c namgen -l world_of_warcraft_pets-wow_pets -d 'Generate World Of Warcraft Pets Wow Pets style names'
