#include "descriptions-humanoids_lib.h"
#include "generator_common.h"
#include <string_view>
#include <string>
#include <iterator>

std::string generate_descriptions_humanoids_name(std::mt19937& rng, int type) {
    static constexpr std::string_view nm1[] = {"Two", "Two", "Two", "Three", "Four", "Two"};
    static constexpr std::string_view nm2[] = {"beady", "broad", "bug-eyed", "clear", "close-set", "dead", "doe-eyed", "enormous", "giant", "glassy", "glowing", "heavy", "hollow", "hooded", "large", "narrow", "shiny", "shuttered", "small", "sunken", "thin", "tiny", "wide"};
    static constexpr std::string_view nm3[] = {"observe", "study", "watch", "inspect", "examine", "monitor", "survey", "look at", "view"};
    static constexpr std::string_view nm4[] = {"narrow", "wide", "broad", "large", "thin", "deep", "huge", "bony"};
    static constexpr std::string_view nm5[] = {"big", "broad", "crooked", "flat", "gentle", "large", "narrow", "pig-like", "pointy", "round", "short", "small", "tiny", "wide"};
    static constexpr std::string_view nm6[] = {"narrow", "large", "wide", "long", "shallow", "deep", "average", "normal", "ordinary", "small"};
    static constexpr std::string_view nm7[] = {"sly", "shy", "wide", "happy", "gentle", "creepy", "brittle", "gummy", "lazy", "sardonic", "thin"};
    static constexpr std::string_view nm8[] = {"sharp", "long", "pointy", "short", "small", "stubby", "dull", "thin", "crooked", "large", "creepy", "eerie"};
    static constexpr std::string_view nm9[] = {"flat", "broad", "thin", "long", "wide", "small", "large"};
    static constexpr std::string_view nm10[] = {"Short", "Long", "Narrow", "Wide", "Broad", "Large", "Small", "Thin"};
    static constexpr std::string_view nm11[] = {"pointy", "round", "bent", "squared"};
    static constexpr std::string_view nm12[] = {"long", "short", "average", "small", "large"};
    static constexpr std::string_view nm13[] = {"narrow", "wide", "thin", "broad", "rounded", "squared", "pointy"};
    static constexpr std::string_view nm14[] = {"thick", "curly", "thin", "long", "short", "wavy", "coarse", "soft", "very long", "silken"};
    static constexpr std::string_view nm15[] = {"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", " and has two small horns protruding from the top", " and has two small horns protruding from the sides", " and has two curved horns protruding from the top", " and has two curved horns protruding from the sides", " and has two stubby horns protruding from the top", " and has two stubby horns protruding from the sides", " and has two thin horns protruding from the top", " and has two thin horns protruding from the sides", " and has two broad horns protruding from the top", " and has two broad horns protruding from the sides"};
    static constexpr std::string_view nm16[] = {"short", "long", "tall", "small", "low", "average"};
    static constexpr std::string_view nm17[] = {"muscular", "broad", "thin", "skinny", "lean", "fat", "slender", "bulky", "chunky", "hefty", "athletic", "stout", "brawny"};
    static constexpr std::string_view nm18[] = {"stands straight", "is slightly hunched over", "is hunched over", "stands straight"};
    static constexpr std::string_view nm19[] = {"long", "thick", "short", "broad", "average", "thin", "lean"};
    static constexpr std::string_view nm20[] = {"dangle", "hang", "rest"};
    static constexpr std::string_view nm21[] = {"small", "gentle", "graceful", "large", "thin", "narrow", "wide", "broad"};
    static constexpr std::string_view nm22[] = {"long", "thick", "thin", "short", "stubby", "small", "curvy"};
    static constexpr std::string_view nm23[] = {"normal", "long", "sharp", "claw-like", "dull", "thin", "pointy", "broad"};
    static constexpr std::string_view nm24[] = {"long", "muscular", "broad", "short", "small", "tall", "wide", "lean", "thin", "skinny"};
    static constexpr std::string_view nm25[] = {"stand straight", "are slightly bent", "are bent", "stand straight"};
    static constexpr std::string_view nm26[] = {"large", "broad", "small", "short", "wide", "big", "hairy", "flat"};
    static constexpr std::string_view nm27[] = {"short fur", "coarse skin", "smooth skin", "soft skin", "delicate skin", "coarse fur", "thick fur", "coarse skin", "smooth skin", "soft skin", "delicate skin", "small scales", "thick skin", "thick scales"};
    static constexpr std::string_view nm28[] = {"broader than", "narrower than", "about the same width as"};
    static constexpr std::string_view nm29[] = {"", "", "", "", "", "", "", "", "", "", "", "", ", from which a long tail sways back and forth", ", from which a short tail sways back and forth", ", from which a broad tail sways back and forth", ", from which a thin tail sways back and forth", ", from which a small tail sways back and forth", ", from which a large tail sways back and forth", ", from which a narrow tail sways back and forth"};
    static constexpr std::string_view nm34[] = {"narrow", "wide", "broad", "large", "thin", "deep", "huge", "bony", "scaly", "eerie", "slimy", "bulging", "enormous", "giant", "tiny"};
    static constexpr std::string_view nm35[] = {"big", "broad", "crooked", "flat", "gentle", "large", "narrow", "pig-like", "pointy", "round", "short", "small", "tiny", "wide", "barely existing", "snake-like", "reptilian", "bony", "spiky", "hollow", "bent", "sharp", "hooked", "thin", "narrow"};
    static constexpr std::string_view nm36[] = {"narrow", "large", "wide", "long", "shallow", "deep", "normal", "small", "huge", "massive", "tiny", "giant", "overbite", "underbite", "enormous"};
    static constexpr std::string_view nm37[] = {"sly", "shy", "wide", "happy", "gentle", "creepy", "brittle", "gummy", "lazy", "sardonic", "thin"};
    static constexpr std::string_view nm38[] = {"rows upon rows of small teeth", "rows upon rows of teeth", "two large fangs", "two small fangs", "two large canines", "two small canines", "rows of eerie looking teeth", "several rows of sharp teeth", "monstrous teeth", "curved fangs", "rows of crooked teeth", "rows of dull teeth", "only a few teeth here and there", "rows of huge teeth", "several huge dull teeth", "several huge sharp teeth", "several large broken teeth", "rows of broken teeth", "rows of shark-like teeth"};
    static constexpr std::string_view nm39[] = {"flat", "broad", "thin", "long", "wide", "small", "large", "very long", "forked", "huge", "coarse", "slimy"};
    static constexpr std::string_view nm40[] = {"Short", "Long", "Narrow", "Wide", "Broad", "Large", "Small", "Thin", "Huge", "Enormous", "Tiny", "Massive"};
    static constexpr std::string_view nm41[] = {"pointy", "round", "bent", "squared", "fan-like", "spiky", "bony", "warped", "hanging", "flappy", "stubby", "wrinkled", "jagged"};
    static constexpr std::string_view nm42[] = {"long", "short", "average", "small", "large", "huge", "tiny", "massive"};
    static constexpr std::string_view nm43[] = {"narrow", "wide", "thin", "broad", "rounded", "squared", "pointy", "oval", "angular", "wrinkled", "lean", "bony", "triangular"};
    static constexpr std::string_view nm44[] = {"long hairs", "coarse hairs", "short hairs", "rows of small horns", "rows of small spikes", "small tentacles", "thin hair-like tentacles", "bony ridges", "bony spikes", "web-like fans", "tiny hairs", "tattoo-like markings", "scar-like carvings", "soft hair", "scaly ridges"};
    static constexpr std::string_view nm45[] = {"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", " and has two small horns protruding from the top", " and has two small horns protruding from the sides", " and has two curved horns protruding from the top", " and has two curved horns protruding from the sides", " and has two stubby horns protruding from the top", " and has two stubby horns protruding from the sides", " and has two thin horns protruding from the top", " and has two thin horns protruding from the sides", " and has two broad horns protruding from the top", " and has two broad horns protruding from the sides", " and has two large tentacles protruding from the top", " and has two large tentacles protruding from the sides", " and has two large antlers protruding from the top", " and has two large antlers protruding from the sides", " and has two bony spikes protruding from the top", " and has two bony spikes protruding from the sides", " and has two huge horns protruding from the top", " and has two huge horns protruding from the sides", " and has two small tentacles protruding from the top", " and has two small tentacles protruding from the sides", " and has two small antlers protruding from the top", " and has two small antlers protruding from the sides", " and has several bony spikes protruding from the top", " and has several bony spikes protruding from the sides", " and has several large tentacles protruding from the top", " and has several large tentacles protruding from the sides"};
    static constexpr std::string_view nm49[] = {"long", "thick", "short", "broad", "average", "thin", "lean"};
    static constexpr std::string_view nm50[] = {"arms", "tentacle-like arms", "bony arms", "almost branch-like arms", "stone-like arms", "fleshy arms", "warping arms", "crooked arms"};
    static constexpr std::string_view nm51[] = {"small", "large", "thin", "narrow", "wide", "broad", "bony", "webbed", "tentacle-like", "claw-like", "bent", "crooked", "massive", "huge", "tiny", "stone-like"};
    static constexpr std::string_view nm52[] = {"long", "thick", "thin", "short", "stubby", "small", "curvy", "bent", "very long", "sharp nailed", "long nailed", "claw-like"};
    static constexpr std::string_view nm53[] = {"6", "8", "10", "12"};
    static constexpr std::string_view nm54[] = {"long", "muscular", "broad", "short", "small", "wide", "lean", "thin", "skinny", "crooked"};
    static constexpr std::string_view nm55[] = {"feet", "hooves", "feet", "paws"};
    static constexpr std::string_view nm56[] = {"large", "broad", "small", "short", "wide", "big", "hairy", "flat", "webbed", "enormous", "massive", "bony", "scaly", "spiky"};
    static constexpr std::string_view nm57[] = {"short fur", "coarse skin", "smooth skin", "soft skin", "delicate skin", "coarse fur", "thick fur", "coarse skin", "smooth skin", "soft skin", "delicate skin", "small scales", "thick skin", "thick scales", "slime", "slimy scales", "large scales", "rock-like scales", "fluffy fur", "nasty skin", "wood-like skin", "small feathers", "large feathers", "feathers", "oily skin", "armor-like scales", "large armor-like scales"};
    static constexpr std::string_view nm59[] = {"", "", "", "", "", "", "", "", "", "", "", "", ", from which a long tail sways back and forth", ", from which a short tail sways back and forth", ", from which a broad tail sways back and forth", ", from which a thin tail sways back and forth", ", from which a small tail sways back and forth", ", from which a large tail sways back and forth", ", from which a narrow tail sways back and forth", ", from which a massive tail sways back and forth", ", from which a bony tail sways back and forth", ", from which a spiked tail sways back and forth", ", from which a tentacle-like tail grows", ", from which a coarse tail sways back and forth", ", from which a split tail sways back and forth", ", from which a forked tail sways back and forth", ", from which a bladed tail sways back and forth", ", from which a fanned tail sways back and forth"};

    std::string name; std::string name2; std::string name3; std::string name4; std::string name5; std::string result; std::string tp; size_t rnd1 = 0; size_t rnd10 = 0; size_t rnd11 = 0; size_t rnd12 = 0; size_t rnd13 = 0; size_t rnd14 = 0; size_t rnd15 = 0; size_t rnd16 = 0; size_t rnd17 = 0; size_t rnd18 = 0; size_t rnd19 = 0; size_t rnd2 = 0; size_t rnd20 = 0; size_t rnd21 = 0; size_t rnd22 = 0; size_t rnd23 = 0; size_t rnd24 = 0; size_t rnd25 = 0; size_t rnd26 = 0; size_t rnd27 = 0; size_t rnd28 = 0; size_t rnd29 = 0; size_t rnd3 = 0; size_t rnd34 = 0; size_t rnd35 = 0; size_t rnd36 = 0; size_t rnd37 = 0; size_t rnd38 = 0; size_t rnd39 = 0; size_t rnd4 = 0; size_t rnd40 = 0; size_t rnd41 = 0; size_t rnd42 = 0; size_t rnd43 = 0; size_t rnd44 = 0; size_t rnd45 = 0; size_t rnd49 = 0; size_t rnd5 = 0; size_t rnd50 = 0; size_t rnd51 = 0; size_t rnd52 = 0; size_t rnd53 = 0; size_t rnd54 = 0; size_t rnd55 = 0; size_t rnd56 = 0; size_t rnd57 = 0; size_t rnd59 = 0; size_t rnd6 = 0; size_t rnd7 = 0; size_t rnd8 = 0; size_t rnd9 = 0; int i = 0;

    tp = type;
    if (tp == 1) {
    rnd1 = rng() % std::size(nm1);
    rnd2 = rng() % std::size(nm2);
    rnd3 = rng() % std::size(nm3);
    rnd34 = rng() % std::size(nm34);
    rnd35 = rng() % std::size(nm35);
    rnd36 = rng() % std::size(nm36);
    rnd37 = rng() % std::size(nm37);
    rnd38 = rng() % std::size(nm38);
    rnd39 = rng() % std::size(nm39);
    rnd40 = rng() % std::size(nm40);
    rnd41 = rng() % std::size(nm41);
    rnd42 = rng() % std::size(nm42);
    rnd43 = rng() % std::size(nm43);
    rnd44 = rng() % std::size(nm44);
    rnd45 = rng() % std::size(nm45);
    rnd16 = rng() % std::size(nm16);
    rnd17 = rng() % std::size(nm17);
    rnd18 = rng() % std::size(nm18);
    rnd49 = rng() % std::size(nm49);
    rnd50 = rng() % std::size(nm50);
    rnd20 = rng() % std::size(nm20);
    rnd51 = rng() % std::size(nm51);
    rnd52 = rng() % std::size(nm52);
    rnd53 = rng() % std::size(nm53);
    rnd54 = rng() % std::size(nm54);
    rnd24 = rng() % std::size(nm24);
    rnd25 = rng() % std::size(nm25);
    rnd55 = rng() % std::size(nm55);
    rnd56 = rng() % std::size(nm56);
    rnd57 = rng() % std::size(nm57);
    rnd28 = rng() % std::size(nm28);
    rnd59 = rng() % std::size(nm59);
    name = nm1[rnd1] + " " + nm2[rnd2] + " eyes " + nm3[rnd3] + " their surroundings from their " + nm34[rnd34] + " sockets. A " + nm35[rnd35] + " nose rests below, but it's the " + nm36[rnd36] + " mouth below that takes all the attention. A " + nm37[rnd37] + " smile reveals " + nm38[rnd38] + " and a " + nm39[rnd39] + " tongue.";
    name2 = nm40[rnd40] + " " + nm41[rnd41] + " ears sit on each side of its " + nm42[rnd42] + ", " + nm43[rnd43] + " head, which itself is covered in " + nm44[rnd44] + nm45[rnd45] + ".";
    name3 = "Its " + nm16[rnd16] + " " + nm17[rnd17] + " body " + nm18[rnd18] + ". Two " + nm49[rnd49] + " " + nm50[rnd50] + " " + nm20[rnd20] + " at its sides and end in " + nm51[rnd51] + " hands with " + nm52[rnd52] + " fingers, of which it has " + nm53[rnd53] + " in total.";
    name4 = "Its legs are " + nm24[rnd24] + " and " + nm25[rnd25] + ", each ending in " + nm54[rnd54] + " " + nm55[rnd55] + ".";
    name5 = "Its body is covered in " + nm57[rnd57] + " and its shoulders are " + nm28[rnd28] + " its pelvis" + nm59[rnd59] + ".";
    } else {
    rnd1 = rng() % std::size(nm1);
    rnd2 = rng() % std::size(nm2);
    rnd3 = rng() % std::size(nm3);
    rnd4 = rng() % std::size(nm4);
    rnd5 = rng() % std::size(nm5);
    rnd6 = rng() % std::size(nm6);
    rnd7 = rng() % std::size(nm7);
    rnd8 = rng() % std::size(nm8);
    rnd9 = rng() % std::size(nm9);
    rnd10 = rng() % std::size(nm10);
    rnd11 = rng() % std::size(nm11);
    rnd12 = rng() % std::size(nm12);
    rnd13 = rng() % std::size(nm13);
    rnd14 = rng() % std::size(nm14);
    rnd15 = rng() % std::size(nm15);
    rnd16 = rng() % std::size(nm16);
    rnd17 = rng() % std::size(nm17);
    rnd18 = rng() % std::size(nm18);
    rnd19 = rng() % std::size(nm19);
    rnd20 = rng() % std::size(nm20);
    rnd21 = rng() % std::size(nm21);
    rnd22 = rng() % std::size(nm22);
    rnd23 = rng() % std::size(nm23);
    rnd24 = rng() % std::size(nm24);
    rnd25 = rng() % std::size(nm25);
    rnd26 = rng() % std::size(nm26);
    rnd27 = rng() % std::size(nm27);
    rnd28 = rng() % std::size(nm28);
    rnd29 = rng() % std::size(nm29);
    name = nm1[rnd1] + " " + nm2[rnd2] + " eyes " + nm3[rnd3] + " their surroundings from their " + nm4[rnd4] + " sockets. A " + nm5[rnd5] + " nose rests below, but it's the " + nm6[rnd6] + " mouth below that takes all the attention. A " + nm7[rnd7] + " smile reveals two " + nm8[rnd8] + " canines and a " + nm9[rnd9] + " tongue.";
    name2 = nm10[rnd10] + " " + nm11[rnd11] + " ears sit on each side of its " + nm12[rnd12] + ", " + nm13[rnd13] + " head, which itself is covered in " + nm14[rnd14] + nm15[rnd15] + " hair.";
    name3 = "Its " + nm16[rnd16] + " " + nm17[rnd17] + " body " + nm18[rnd18] + ". Two " + nm19[rnd19] + " arms " + nm20[rnd20] + " at its sides and end in " + nm21[rnd21] + " hands with " + nm22[rnd22] + " fingers, each with " + nm23[rnd23] + " nails.";
    name4 = "Its legs are " + nm24[rnd24] + " and " + nm25[rnd25] + ", each ending in " + nm26[rnd26] + " feet.";
    name5 = "Its body is covered in " + nm27[rnd27] + " and its shoulders are " + nm28[rnd28] + " its pelvis" + nm29[rnd29] + ".";
    }
    result = "";
    result += name;
    result += "\n";
    result += name2;
    result += "\n";
    result += "\n";
    result += name3;
    result += "\n";
    result += name4;
    result += "\n";
    result += "\n";
    result += name5;
    return result;
}
