#include <random>
#include <string>
#include <vector>
#include <array>
#include <algorithm>
#include <cstddef>

/* Return a random integer in the range [0, max) using the supplied RNG. */
static std::size_t rand_index(std::mt19937& rng, std::size_t max) {
    std::uniform_int_distribution<std::size_t> dist(0, max - 1);
    return dist(rng);
}

/* Small subset of the original `nm1` array from elfs.js – each entry is
   a pair of <prefix, meaning>.  The meaning is kept for possible future
   extensions but is not used by the current generator. */
static const std::vector<std::array<std::string, 2>> elf_prefixes = {
    {"Âr", "Royal/Noble"},
    {"Êg", "Thorn"},
    {"Êl", "Star"},
    {"Îdh", "Rest/Repose"},
    {"Îr", "Sexual Desire"},
    {"Óleryd", "Dream of Mountains"},
    {"Ôl", "Dream"},
    {"Úan", "Monster"},
    {"Úhael", "Unwise"},
    {"Úlloth", "Flower Scent"},
    {"Úthaes", "Temptation"},
    {"Ûn", "Creature"},
    {"Ûr", "Fire"},
    {"Ûr", "Wide/Heat"},
    {"Ýridhren", "Wise Course"},
    {"Ablad", "Prohibition/Refusal"},
    {"Acharn", "Vengeance"},
    {"Achas", "Dread/Fear"},
    {"Adab", "Building/House"},
    {"Aduial", "Evendim"},
    {"Aear", "Sea"},
    {"Aearon", "Ocean"},
    {"Aeg", "Sharp Point"},
    {"Aeglos", "Icicle"},
    {"Ael", "Lake/Pool"},
    {"Aen", "Holy"},
    {"Aer", "Holy"},
    {"Aer", "Sea"},
    {"Aew", "Small Bird"},
    {"Aewen", "Of Birds"},
    {"Agar", "Blood"},
    {"Agarwaen", "Bloodstained"},
    {"Aglar", "Glory/Brilliance"},
    {"Aglareb", "Glorious"},
    {"Agor", "Narrow"},
    {"Aith", "Spearpoint"},
    {"Alag", "Rushing/Impetuous"},
    {"Alagos", "Wind Storm"},
    {"Alph", "Swan"},
    {"Amar", "Earth"},
    {"Amarth", "Fate/Doom"},
    {"Amath", "Shield"},
    {"Amlug", "Dragon"},
    {"Amon", "Hill"},
    {"Amrûn", "East"},
    {"And", "Long"},
    {"Ang", "Iron"},
    {"Angol", "Deep Lore/Magic"},
    {"Angol", "Stench"},
    {"Angwedh", "Chain"},
    {"Annúngil", "West Star"},
    {"Annûn", "West/Sunset"},
    {"Annon", "Door/Gate"},
    {"Annui", "Western"},
    {"Ant", "Gift"},
    {"Anu", "Masculine"},
    {"Aradhel", "Royal Terror"},
    {"Arahael", "Noble and Wise"},
    {"Aras", "Deer"},
    {"Arn", "Royal"},
    {"Arod", "Noble"},
    {"Arrad", "Without a Path"},
    {"Arth", "Exalted"},
    {"Aur", "Day/Sunlight"},
    {"Auth", "Spectral/Apparition"},
    {"Auth", "War/Battle"},
    {"Avorn", "Staying/Fast"},
    {"Bôr", "Faithful Man/Vassal"},
    {"Bachor", "Pedlar"},
    {"Bain", "Beautiful"},
    {"Baingol", "Fair and Wise"},
    {"Balch", "Cruel"},
    {"Ballin", "Divine"},
    {"Balrant", "Powerful Course"},
    {"Band", "Prison"},
    {"Bar", "Dwelling/Home"},
    {"Bara", "Fiery"},
    {"Barad", "Doomed"},
    {"Barad", "Tower/Fortress"},
    {"Baralin", "Fiery Gleam in the Eyes"},
    {"Baran", "Brown"},
    {"Barhador", "One Faithful to Home"},
    {"Baudh", "Judgement"},
    {"Baug", "Tyrannous/Cruel"},
    {"Baul", "Torment"},
    {"Baur", "Need"},
    {"Beleg", "Great/Mighty"},
    {"Belegorn", "Mighty Tree"},
    {"Belegur", "Great Heart"},
    {"Belt", "Strong"},
    {"Beren", "Bold"},
    {"Born", "Fiery Red"},
    {"Bornif", "Fiery Red Face"},
    {"Both", "Puddle/Small Pool"},
    {"Brêg", "Violent/Sudden/Fierce"},
    {"Brûn", "Old"},
    {"Bragol", "Sudden"},
    {"Braig", "Wild/Fierce"},
    {"Brand", "High/Noble/Fine"},
    {"Brass", "White Heat"},
    {"Breged", "Violence/Suddenness"},
    {"Bregol", "Violent/Fierce"},
    {"Brethil", "Beech"},
    {"Bronad", "Survival"},
    {"Bronwe", "Endurance/Faith"},
    {"Brui", "Loud/Noisy"},
    {"Cîl", "Cleft/Gorge"},
    {"Cîl", "Renewal"},
    {"Cîr", "Renewed"},
    {"Cîw", "Fresh/New"},
    {"Côf", "Bay"},
    {"Côl", "Gold"},
    {"Cû", "Bow"},
    {"Cûn", "Bow-shaped/Bent"},
    {"Cadu", "Shaped/Formed"},
    {"Cadwor", "Shapely"},
    {"Cae", "Earth"},
    {"Cael", "Sickness"},
    {"Caeleb", "Bedridden/Sick"},
    {"Caew", "Lair"},
    {"Cai", "Hedge"},
    {"Cail", "Sharp Fence"},
    {"Cair", "Ship"},
    {"Calad", "Light"},
    {"Calaer", "Light of the Sea"},
    {"Calar", "Lamp"},
    {"Calardan", "Lampwright"},
    {"Caledhel", "Light Elf"},
    {"Calemir", "Green Jewel"},
    {"Calen", "Green"},
    {"Calithil", "Moon Light"},
    {"Callon", "Hero"},
    {"Calph", "Water-Vessel"},
    {"Camaen", "Skilled Hand"},
    {"Cand", "Bold"},
    {"Caran", "Red"},
    {"Carandol", "Red Head"},
    {"Caranor", "Red Fire"},
    {"Caraphind", "Red Hair"},
    {"Caras", "City"},
    {"Cast", "Cape/Cove"},
    {"Caun", "Valor"},
    {"Cef", "Soil"},
    {"Celair", "Brilliant"},
    {"Celeb", "Silver"},
    {"Celeblas", "Silver Leaf"},
    {"Celebren", "Silvery"},
    {"Celeg", "Swift/Agile/Hasty"},
    {"Celephind", "Silver Tresses"},
    {"Cellin", "Flowing Music"},
    {"Celon", "River"},
    {"Cennan", "Potter"},
    {"Ceven", "Earthen"},
    {"Claur", "Splendour/Glory"},
    {"Colfind", "Gold Hair"},
    {"Coll", "Golden Red"},
    {"Corch", "Crow"},
    {"Coru", "Cunning"},
    {"Cost", "Quarrel"},
    {"Coth", "Enemy"},
    {"Craban", "Raven"},
    {"Cugu", "Dove"},
    {"Curu", "Skilled"},
    {"Curulaer", "Song Skill"},
    {"Dílloth", "Silent Flower"},
    {"Dínen", "Silent"},
    {"Dôl", "Hill/Mountain"},
    {"Dúlind", "Nightingale"},
    {"Dúven", "Southern"},
    {"Dû", "Nightfall"},
    {"Dûr", "Dark"},
    {"Dûr", "Somber"},
    {"Dae", "Shadow"},
    {"Daedhel", "Shadow of Horror"},
    {"Daedhrog", "Shadow Wolf"},
    {"Daer", "Great"},
    {"Dam", "Hammer"},
    {"Dath", "Hole/Pit/Abyss"},
    {"Daug", "Warrior/Soldier"},
    {"Daw", "Night/Gloom"},
    {"Del", "Fear/Disgust"},
    {"Deldhin", "Silent Horror"},
    {"Deleb", "Horrible/Loathsome"},
    {"Delgaran", "Red Horror"},
    {"Delos", "Detestation/Loathing"},
    {"Delu", "Hateful/Deadly/Fell"},
    {"Dem", "Sad/Gloomy"},
    {"Dimaethor", "Silence Warrior"},
    {"Dinalagos", "Silent Storm"},
    {"Doll", "Dark/Dusky"},
    {"Doron", "Oak"},
    {"Draug", "Wolf"},
    {"Dringol", "Wise Hammerer"},
    {"Duin", "River"},
    {"Duinen", "Flood/High Tide"},
    {"Duirro", "River-Bank"},
    {"Duvain", "Beautiful Darkness"},
    {"Ech", "Spine"},
    {"Echad", "Camp"},
    {"Echui", "Awakening"},
    {"Ecthel", "Spearpoint"},
    {"Eden", "New"},
    {"Edlen", "Exiled"},
    {"Edraith", "Saving"},
    {"Eglan", "Forsaken"},
    {"Egnas", "Sharp Point"},
    {"Eiliant", "Rainbow"},
    {"Elhael", "Wise Elf"},
    {"Ellavorn", "Staying Elf"},
    {"Elu", "Light Blue"},
    {"Emlin", "Yellow Bird"},
    {"Ened", "Centre/Middle"},
    {"Ephel", "Outer Fence"},
    {"Erch", "Prickle"},
    {"Eredh", "Seed"},
    {"Erist", "Lone Lore"},
    {"Erthor", "Uniter"},
    {"Eru", "Waste/Desert"},
    {"Erwarth", "Lone Betrayer"},
    {"Eryn", "Woods"},
    {"Esgal", "Screen/Veil"},
    {"Esgalnor", "Hiding Fire"},
    {"Esgalwath", "Hiding Shadow"},
    {"Esgar", "Shore"},
    {"Estel", "Hope/Trust"},
    {"Estelmist", "Lost Hope"},
    {"Estent", "Short"},
    {"Estolad", "Encampment"},
    {"Ethir", "River Mouth/Estuary"},
    {"Ethir", "Spy"},
    {"Fân", "Bright Figure/Veil/White Cloud"},
    {"Fêr", "Beech-Tree"},
    {"Faeg", "Bad/Mean/Poor"},
    {"Fael", "Generous"},
    {"Faen", "Radiant White"},
    {"Faerdhinen", "Silent Spirit"},
    {"Faerthurin", "Secret Spirit"},
    {"Faervel", "Strong Spirit"},
    {"Faerveren", "Joyous Spirit"},
    {"Fain", "Cloud"},
    {"Fain", "White"},
    {"Falas", "Beach"},
    {"Falch", "Ravine"},
    {"Fang", "Beard"},
    {"Far", "Sufficient"},
    {"Fast", "Shaggy Hair"},
    {"Faug", "Thirsty"},
    {"Faun", "Cloud"},
    {"Faur", "Beach/Shore"},
    {"Fela", "Cave"},
    {"Fend", "Door/Threshold"},
    {"Fileg", "Little Birds"},
    {"Fim", "Slender"},
    {"Fingaer", "Coppery Red Hair"},
    {"Forn", "North"},
    {"Forod", "North"},
    {"Forven", "North"},
    {"Fuin", "Night/Darkness"},
    {"Fuir", "North"},
    {"Gûd", "Foe"},
    {"Gûl", "Sorcery"},
    {"Gûr", "Death"},
    {"Gûr", "Heart/Counsel"},
    {"Gador", "Prison/Dungeon"},
    {"Gae", "Dread"},
    {"Gaear", "Sea"},
    {"Gael", "Pale/Glimmering"},
    {"Gaer", "Coppery Red"},
    {"Gaer", "Dreadful"},
    {"Gaer", "Sea"},
    {"Gaeralagos", "Sea Storm"},
    {"Gaeruil", "Seaweed"},
    {"Gail", "Star/Bright Light"},
    {"Gal", "Light"},
    {"Galad", "Light/Radiance"},
    {"Galadh", "Tree"},
    {"Galas", "Plant"},
    {"Galenas", "Pipeweed"},
    {"Galu", "Good Fortune"},
    {"Gamp", "Hook/Claw"},
    {"Gannel", "Harp"},
    {"Garaf", "Wolf"},
    {"Garth", "Fortress"},
    {"Gas", "Hole"},
    {"Gath", "Cavern"},
    {"Gathrod", "Cave"},
    {"Gaud", "Machine"},
    {"Gaul", "Wolf-Howl"},
    {"Gaur", "Werewolf"},
    {"Gaw", "Void"},
    {"Gawad", "Howling"},
    {"Gelinnas", "Joyful Will"},
    {"Gell", "Joy/Triumph"},
    {"Gellam", "Jubilation"},
    {"Gellui", "Triumphant"},
    {"Gem", "Sickly"},
    {"Gern", "Old/Decripit"},
    {"Gilorn", "Star Tree"},
    {"Girith", "Shuddering/Horror"},
    {"Glân", "White"},
    {"Glî", "Honey"},
    {"Glîn", "Gleam/Glint"},
    {"Glîr", "Song"},
    {"Glûdh", "Soap"},
    {"Glaew", "Salve"},
    {"Glam", "Shouting/Uproar"},
    {"Glamor", "Echo"},
    {"Glamren", "Echoing"},
    {"Glass", "Joy"},
    {"Glaur", "Golden Light"},
    {"Glavrol", "Babbling"},
    {"Glaw", "Radiance"},
    {"Glawar", "Sunlight/Radiance"},
    {"Gloss", "Snow-White"},
    {"Gobel", "Town"},
    {"Goe", "Terror"},
    {"Goeol", "Dreadful/Terrifying"},
    {"Golf", "Branch"},
    {"Goll", "Wise"},
    {"Gollor", "Magician"},
    {"Golwen", "Wise"},
    {"Gond", "Stone/Rock"},
    {"Gorf", "Vigor"},
    {"Gorfuin", "Dreaded Gloom"},
    {"Gorn", "Impetuous/Valor"},
    {"Gorog", "Horror"},
    {"Goroth", "Horror"},
    {"Gorth", "Horror"},
    {"Gorthad", "Barrow"},
    {"Gortheb", "Horrible"},
    {"Gost", "Dread"},
    {"Gowest", "Contract/Treaty"},
    {"Graw", "Bear"},
    {"Grond", "Club"},
    {"Groth", "Cave/Tunnel"},
    {"Gruin", "Ruddy"},
    {"Guldur", "Black Magic"},
    {"Gurgaran", "Red Death"},
    {"Gurth", "Death"},
    {"Guruth", "Death"},
    {"Gwî", "Net/Web"},
    {"Gwaedh", "Bond/Oath"},
    {"Gwael", "Gull"},
    {"Gwaen", "Stained"},
    {"Gwaeren", "Windy"},
    {"Gwaew", "Wind"},
    {"Gwain", "New"},
    {"Gwas", "Stain"},
    {"Gwastar", "Hummock"},
    {"Gwath", "Shade/Shadow"},
    {"Gwaun", "Goose"},
    {"Gwaur", "Soiled/Dirty"},
    {"Gwedh", "Bond"},
    {"Gwelu", "Air"},
    {"Gwend", "Bond/Friendship"},
    {"Gwilith", "Air"},
    {"Gwilwileth", "Butterfly"},
    {"Gwing", "Spindrift/Foam"},
    {"Hâdh", "Cleaver"},
    {"Hâl", "Fish"},
    {"Hîw", "Sticky"},
    {"Hû", "Dog"},
    {"Hûb", "Haven/Harbor/Bay"},
    {"Hûl", "Battle Cry"},
    {"Hûr", "Vigour/Fiery Spirit"},
    {"Habad", "Shoe"},
    {"Hadlath", "Sling"},
    {"Hae", "Far/Remote/Distant"},
    {"Haedirn", "Remote Watcher"},
    {"Haered", "Remote Distance"},
    {"Haerel", "Distant Star"},
    {"Haeron", "Far/Remote/Distant"},
    {"Haew", "Custom/Habit"},
    {"Half", "Seashell"},
    {"Hall", "Exalted"},
    {"Hall", "Tall/Hidden"},
    {"Halloth", "Hiding Flower"},
    {"Ham", "Chair"},
    {"Hand", "Intelligent"},
    {"Harad", "South"},
    {"Haradren", "Southern"},
    {"Harn", "Helmet"},
    {"Harn", "Southern"},
    {"Harn", "Wounded"},
    {"Haru", "Wound"},
    {"Hast", "Axe-Stroke"},
    {"Hathol", "Blade/Axe"},
    {"Haudh", "Tomb"},
    {"Haust", "Bed"},
    {"Helch", "Bitter Cold"},
    {"Heledh", "Glass"},
    {"Heledir", "Kingfisher"},
    {"Heleg", "Ice"},
    {"Heleth", "Fur/Fur-Coat"},
    {"Helf", "Fur"},
    {"Hell", "Naked"},
    {"Henneth", "Window"},
    {"Hethurin", "Secret Child"},
    {"Him", "Cold"},
    {"Him", "Steadfast/Abiding"},
    {"Himel", "Cold Star"},
    {"Hinnor", "Fire Eyes"},
    {"Hissael", "Wise Eyes"},
    {"Hith", "Mist/Fog"},
    {"Hithaer", "Sea Mist"},
    {"Hithfaer", "Mist Spirit"},
    {"Hithu", "Fog"},
    {"Horn", "Driven/Impelled"},
    {"Hwest", "Breeze"},
    {"Hwind", "Twirling/Whirling"},
    {"Iâ", "Abyss"},
    {"Iâr", "Blood"},
    {"Iôl", "Flood Plain"},
    {"Iûl", "Embers"},
    {"Iach", "Ford/Crossing"},
    {"Iaew", "Mocking/Scorn"},
    {"Ial", "Call/Cry"},
    {"Iant", "Bridge"},
    {"Ianu", "Yoke"},
    {"Iau", "Corn"},
    {"Iau", "Ravine/Gulf"},
    {"Iaun", "Sanctuary"},
    {"Iaur", "Ancient/Old"},
    {"Idhren", "Wise/Thoughtful"},
    {"Iest", "Wish"},
    {"Inc", "Guess/Idea/Notion"},
    {"Ind", "Inner Thought/Meaning/Heart"},
    {"Ingem", "Old/Year-Sick"},
    {"Inu", "Feminine"},
    {"Iorist", "Ancient Lore"},
    {"Iorthon", "Old Pine"},
    {"Iphant", "Aged/Old"},
    {"Ist", "Knowledge/Lore"},
    {"Istui", "Learned"},
    {"Ivor", "Crystal"}
};

/* Small subset of the original `nm2` array – each entry is a pair
   <verb, meaning> */
static const std::vector<std::array<std::string, 2>> elf_verbs = {
    {"Gal", "To Sing"},
    {"Gur", "To Run"},
    {"Lir", "To Laugh"}
};

/* Generate an ELF name by randomly combining a prefix and a verb.
   The `type` parameter is currently unused but kept for API compatibility. */
std::string generate_lotr_elf_name(int /*type*/) {
    static std::mt19937 rng(std::random_device{}());

    // Choose a random prefix
    const std::string& prefix = elf_prefixes[rand_index(rng, elf_prefixes.size())][0];

    // Choose a random verb (if we have any)
    std::string verb;
    if (!elf_verbs.empty()) {
        verb = elf_verbs[rand_index(rng, elf_verbs.size())][0];
    }

    // Simple concatenation – you can adjust the format as needed.
    return prefix + verb;
}
