#include "pop_culture-arthurians_lib.h"
#include "generator_common.h"
#include <string_view>
#include <string>
#include <iterator>

std::string generate_pop_culture_arthurians_name(std::mt19937& rng, int type) {
    static constexpr std::string_view names1[] = {"Acca", "Acco", "Adda", "Afa", "Aglo", "Agloua", "Agra", "Alai", "Albi", "Ale", "Ali", "Amfo", "Ance", "Andre", "Ani", "Anto", "Apo", "Ara", "Arte", "Arthga", "Arthu", "Artu", "Augu", "Ava", "Awa", "Ba", "Bagde", "Baldu", "Be", "Beau", "Bedi", "Bella", "Bersu", "Bi", "Bla", "Blai", "Bleo", "Blia", "Blya", "Bo", "Boho", "Bra", "Brande", "Bre", "Bredbe", "Breu", "Brie", "Bru", "Ca", "Cadwa", "Cae", "Cai", "Cali", "Calo", "Camla", "Cara", "Cara", "Carli", "Carnwe", "Chapa", "Cla", "Clame", "Clau", "Colgre", "Consta", "Cunobe", "Custe", "Cymbe", "Cynfa", "Cyny", "Dago", "Dague", "Dina", "Dodi", "Dru", "Drua", "Dry", "Ecto", "Eli", "Elia", "Eliau", "Elya", "Emry", "Erbi", "Ere", "Escla", "Esco", "Eva", "Eve", "Evra", "Evrai", "Fale", "Flo", "Ga", "Gaha", "Gahe", "Gahmu", "Gala", "Gale", "Gare", "Gau", "Ge", "Gi", "Glai", "Glati", "Gle", "Go", "Gorla", "Gouve", "Gri", "Gue", "Gui", "Guio", "Gwa", "Gwalcha", "Gwe", "Gwio", "Gwy", "He", "Helle", "Ho", "Hoe", "Hua", "Huo", "Hy", "Isde", "Iwai", "Jo", "Ka", "Kady", "Kahe", "Kai", "Kay", "Keri", "Keu", "Ki", "Ky", "Kynthe", "La", "Lai", "Lamo", "Lance", "Lao", "Lau", "Launce", "Leo", "Leode", "Leodo", "Lio", "Lla", "Lle", "Llu", "Llua", "Lly", "Lo", "Lohe", "Lu", "Ma", "Mahe", "Me", "Melea", "Melia", "Mo", "Mo", "Na", "Ne", "Oza", "Pa", "Pala", "Palo", "Parzi", "Passe", "Pe", "Pelle", "Pelli", "Pendra", "Perci", "Percy", "Pere", "Peri", "Phe", "Rhongo", "Rhy", "Rhye", "Rie", "Rio", "Riva", "Rye", "Sa", "Sagra", "Sagre", "Segwa", "Spuma", "Ta", "Tei", "To", "Trevri", "Tri", "Urie", "Uthe", "Uwai", "Vale", "Vorti", "Walga", "Yde", "Yspa", "Yuei", "Yvai", "Ywai", "Ywai"};
    static constexpr std::string_view names2[] = {"bal", "beris", "bon", "breul", "bron", "burn", "buz", "can", "cas", "ce", "cheu", "chlyn", "cius", "coir", "ctacus", "ctor", "dain", "dak", "dan", "das", "dawc", "dawg  ", "dd", "ddaden", "dderch", "ddle", "deam", "degan", "deus", "doc", "dor", "dos", "dred", "drod", "dud", "dur", "dure", "dus", "dver", "dwg", "dwyn", "dwyr", "fbras", "ffire", "fir", "flet", "gal", "gant", "gern", "gon", "gor", "gran", "graunce", "grenant", "had", "halt", "han", "hem", "hfrit", "hoot", "hot", "kin", "ladr", "laine", "lake", "lan", "lchmai", "lduc", "le", "len", "les", "lf", "lhwch", "lig", "lin", "line", "linus", "lis", "llach", "llam", "llean", "lleas", "llech", "lles", "llo", "lloc", "llon", "llwch", "loas", "loken", "lon", "lot", "lu", "lwas", "lydd", "magus", "mains", "mar", "medes", "mer", "mides", "mones", "mor", "mour", "myant", "n", "nc", "nce", "ne", "nel", "nell", "ner", "net", "nfal", "ngere", "ngist", "ngolet", "ngrin", "ngroen", "nham", "nn", "nna", "nnan", "nnin", "nnus", "nor", "nore", "ns", "nt", "ntine", "ntres", "nus", "nw", "r", "raint", "rak", "rant", "rard", "raunt", "rch", "rddhin", "rdeiz", "rdin", "rdred", "redin", "rehes", "rence", "rent", "res", "ret", "reu", "rflet", "rholt", "riath", "rides", "riet", "rin", "rion", "ris", "rk", "rleon", "rlin", "rlois", "rlon", "rnach", "rnail", "rnus", "ron", "rrok", "rs", "rsa", "rt", "rtas", "rwar", "s", "sant", "scien", "se", "sel", "selus", "sle", "ssar", "st", "stan", "stram", "t", "th", "thi", "tine", "vain", "val", "vale", "vall", "vance", "ved", "velle", "vere", "vres", "vret", "w", "wain", "wel", "wg", "wlwyd", "wn", "wr", "xander", "zent"};
    static constexpr std::string_view names3[] = {"Aglo", "Ali", "Andre", "Angha", "Ara", "Arthwy", "Asto", "Ava", "Be", "Bedi", "Bela", "Bella", "Bla", "Blai", "Bleo", "Bra", "Bre", "Carnwe", "Cla", "Colgre", "Condwi", "Cu", "Cy", "Danbra", "Dina", "Dindra", "Eli", "Elia", "Eliau", "Elya", "Emry", "Engre", "Etta", "Eva", "Eve", "Flo", "Ga", "Gahe", "Gle", "Gui", "Gwy", "Gyne", "Helai", "Helle", "Ho", "Hy", "Igrai", "Kady", "Kahe", "Ki", "La", "Me", "Mo", "Olwe", "Owai", "Oza", "Pe", "Pelli", "Peri", "Phe", "Sa", "Te", "Tei", "Ywai", "Ywai"};
    static constexpr std::string_view names4[] = {"beris", "dan", "deam", "dron", "dure", "dwyr", "ffire", "fir", "gan", "kane", "kin", "lake", "lat", "line", "llean", "lleas", "lles", "llo", "lon", "lydd", "mbe", "mones", "mour", "mri", "n", "ndelis", "ne", "ngaine", "ngere", "ngoire", "ngwain", "nham", "nn", "nna", "nnan", "nnin", "nore", "rad", "ramur", "ramurs", "rat", "rawd", "rd  ", "rddhin", "rdin", "redin", "rence", "rent", "res", "riath", "rion", "ris", "rre", "rsa", "rvudd", "rvydd", "s", "se", "ste", "th", "thi", "vale", "vance", "vere", "vres", "vret", "wain", "wel", "wlwyd", "wn"};
    static constexpr std::string_view names5[] = {"Ache", "Ade", "Ana", "Angha", "Angli", "Anna", "Arga", "Asto", "Ava", "Bela", "Blanche", "Bra", "Bre", "Bro", "Che", "Cla", "Clari", "Condwi", "Cu", "Danbra", "Dechte", "Dindra", "Ei", "Elai", "Eliza", "Elsa", "Eni", "Eny", "Essy", "Estri", "Esy", "Etta", "Feni", "Flo", "Galie", "Ganie", "Grisa", "Gue", "Guene", "Gui", "Guine", "Gwe", "Gwendo", "Gwene", "Gwenhwy", "Gyne", "Helai", "Herze", "Ibli", "Ige", "Igrai", "Isabe", "Iseu", "Ishi", "Iso", "Ku", "La", "Lau", "Li", "Line", "Lisa", "Lla", "Lu", "Lyne", "Lyo", "Marga", "Mati", "Mo", "Morca", "Morgau", "Ni", "Olwe", "Orca", "Pry", "Sebi", "Sha", "Si", "Sore", "Te", "Vi", "Yge", "Ygrai", "Yseu"};
    static constexpr std::string_view names6[] = {"beth", "ce", "d", "da", "damor", "damors", "de", "des", "dine", "dron", "dwen", "fach", "far", "fleur", "flor", "flour", "gan", "gau", "geus", "gune", "gyr", "kane", "lat", "ld", "lda", "lde", "len", "linda", "linde", "lla", "lle", "llt", "loena", "lon", "lott", "loyde", "lt", "lte", "mrei", "mri", "mue", "na", "nddydd", "ndole", "ndrie", "ndry", "ne", "ned", "nes", "nesse", "net", "nete", "neve", "never", "ngaine", "ngwain", "nloie", "nna", "nor", "nors", "nte", "nwen", "rad", "ramur", "ramurs", "rat", "rawd", "rd", "re", "ree", "rine", "rne", "rre", "rvudd", "rvydd", "se", "ssant", "th", "tte", "vach", "var", "ver", "vere", "viana", "vien", "wse"};

    std::string names; size_t rnd = 0; size_t rnd2 = 0; int i = 0;

i = rng() % 10; {
    if (type == 1) {
    rnd = rng() % std::size(names5);
    rnd2 = rng() % std::size(names6);
    names = names5[rnd] + names6[rnd2];
    } else if (type == 2) {
    rnd = rng() % std::size(names3);
    rnd2 = rng() % std::size(names4);
    names = names3[rnd] + names4[rnd2];
    } else {
    rnd = rng() % std::size(names1);
    rnd2 = rng() % std::size(names2);
    names = names1[rnd] + names2[rnd2];
    }
    return names;
    }
}
