#include "real-colonial_americans_lib.h"
#include "generator_common.h"
#include <string_view>
#include <string>
#include <iterator>

std::string generate_real_colonial_americans_name(std::mt19937& rng, int type) {
    static constexpr std::string_view nm1[] = {"Abel", "Abiel", "Abijah", "Abimael", "Abner", "Abraham", "Absalom", "Adonijah", "Ajax", "Alden", "Amias", "Amiel", "Ammiras", "Amos", "Amzi", "Ansel", "Archibald", "Asa", "Asahel", "Azariah", "Balthasar", "Barnabas", "Bartholomew", "Bazel", "Benajah", "Boaz", "Chauncey", "Christopher", "Clement", "Comfort", "Constant", "Cotton", "Cyrus", "Degory", "Duncan", "Ebenezer", "Edward", "Elbert", "Eleazar", "Eleazer", "Eli", "Eliab", "Eliakim", "Elias", "Elihu", "Elijah", "Eliphalet", "Elisha", "Emanuel", "Emory", "Enoch", "Enos", "Ephraim", "Experience", "Ezekiel", "Francis", "Garvan", "Gawen", "Gerrard", "Gideon	", "Gideon", "Giles", "Hannibal", "Henry", "Hercules", "Hezekiah", "Hiram", "Holmes", "Homer", "Horatio", "Hosea", "Increase", "Isaac", "Isaiah", "Isham", "Israel", "Jabez", "James", "Jared", "Jasper", "Jedidiah", "Jehu", "Jeremiah", "Jethro", "Job", "John", "Jonas", "Josiah", "Jothan", "Kenelm", "Lazarus", "Lemuel", "Levi", "Linus", "Love", "Matthias", "Micajah", "Miles", "Moses", "Myles", "Nehemiah", "Noble", "Obadiah", "Oceanus", "Philo", "Philomon", "Phineas", "Prosperity", "Reason", "Resolved", "Richard", "Robert", "Rufus", "Salmon", "Sampson", "Samuel", "Seth", "Silas", "Simon", "Solomon", "Thaddeus", "Theophilus", "Thomas", "Truth", "William", "Wrestling", "Zaccheus", "Zachariah", "Zadock", "Zadok", "Zebulon", "Zephaniah", "Zophar"};
    static constexpr std::string_view nm2[] = {"Abigail", "Abitha", "Alice", "Amity", "Ann", "Anne", "Aphra", "Aurinda", "Azuba", "Candace", "Catherine", "Charity", "Charlotte", "Chastity", "Clarity", "Comfort", "Constance", "Cornelia", "Damarus", "Deliverance", "Desire", "Dorcas", "Dorothy", "Edith", "Eleanor", "Electa", "Eliza", "Elizabeth", "Ellen", "Emeline", "Ester", "Esther", "Experience", "Fanny", "Felicity", "Fidelity", "Georgine", "Grace", "Harriet", "Hecuba", "Helen", "Henrietta", "Hephzibah", "Hepzibah", "Hester", "Humility", "Increase", "Isabella", "Jane", "Joan", "Joy", "Judith", "Katherine", "Keturah", "Keziah", "Lydia", "Mahala", "Martha", "Mary", "Mercy", "Modesty", "Patience", "Phila", "Phoebe", "Piety", "Primrose", "Priscilla", "Prosperity", "Prudence", "Reason", "Rebekah", "Remember", "Rosanna", "Rose", "Sarah", "Selah", "Silence", "Susanna", "Tabitha", "Temperance", "Thankfull", "Theodosia", "Truth", "Verity", "Virginia", "Zipporah"};
    static constexpr std::string_view nm3[] = {"Adair", "Adams", "Aigar", "Alexander", "Allen", "Alloways", "Amos", "Anderson", "Andrews", "Atkins", "Attyte", "Badders", "Bailey", "Baird", "Barnard", "Barnet", "Barnett", "Barton", "Bean", "Bennett", "Best", "Bohannon", "Bohnanon", "Bond", "Bourne", "Bowles", "Boyd", "Bradley", "Bradshaw", "Brady", "Brannon", "Brown", "Buchannon", "Caldwell", "Camble", "Carson", "Chamberlain", "Chambers", "Channel", "Clark", "Clement", "Clements", "Collins", "Cooper", "Cord", "Cornelius", "Couzens", "Cowan", "Cowgil", "Cowgill", "Crawford", "Cresswell", "Criswel", "Crockett", "Cromey", "Crummey", "Cunningham", "Curley", "Davison", "Dickson", "Dinsmore", "Dixon", "Dodson", "Donald", "Donnell", "Doran", "Doras", "Duncan", "Dunlap", "Eastburn", "Eaton", "Ebaugh", "Edgar", "Edmiston", "Edmundson", "Elder", "Emenheiser", "Emmitt", "Erwin", "Ewing", "Fansant", "Farr", "Feit", "Foster", "Fulton", "Galbraith", "Gale", "Gest", "Gibson", "Gillcrest", "Glasgow", "Gordon", "Gorley", "Graham", "Graydon", "Griffith", "Grove", "Growden", "Hair", "Hall", "Hamilton", "Hartman", "Hawkins", "Hershey", "Hill", "Hopkins", "Hughey", "Irwin", "Jarret", "Jarrett", "John", "Johnston", "Jones", "Jordan", "Kenly", "Kennard", "Kersey", "Kilgore", "Kimble", "Kincaid", "Kinnard", "Kirk", "Kisiner", "Lanius", "Lawson", "Leeper", "Lewden", "Ligget", "Liggett", "Liggit", "Lineboro", "Litten", "Livingston", "Lukey", "Mackey", "Major", "Manifold", "Mantle", "Mare", "Marlin", "Martin", "Mason", "Matthews", "McCalla", "McCalmont", "McCanless", "McCaskey", "McClelland", "McClemont", "McConnal", "McConnel", "McCord", "McCourtney", "McCoy", "McCullough", "McCurdy", "McDaniel", "McFadden", "McGee", "McMullen", "McNamee", "McPherson", "Means", "Mears", "Miller", "Milligen", "Millikan", "Milliken", "Mitchell", "Moffett", "Montgomery", "Morgan", "Morris", "Morrison ", "Munn", "Murphy", "Murray", "Neiper", "Nichol", "Nichols", "Nickle", "O’Brian", "Obrian", "Oliver", "Onion", "Osborn", "PERKINGS", "Paine", "Parker", "Patterson", "Payne", "Pedan", "Pennel", "Perkins", "Peters", "Pickart", "Pierson", "Poole", "Power", "Price", "Purdy", "Pymer", "Quigly", "Ramsey", "Redman", "Reed", "Richardson", "Robinson", "Rogers", "Roland", "Ross", "Rouse", "Rowan", "Sample", "Schotts", "Scott", "Scotts", "Semple", "Siddall", "Sinclair", "Sinkler", "Smille", "Smith", "Snyder", "Stalsworth", "Stedman", "Steel", "Sterret", "Sterrett", "Stevenson", "Stewart", "Suitor", "Switzer", "Taggert", "Taylor", "Templeton", "Thompson", "Tomkin", "Toule", "Traverse", "Vansant", "Wallace", "Watt", "Webb", "Wentz", "West", "White", "Whiteford", "Whitelock", "Wiley", "Williams", "Williamson", "Wilson", "Wise", "Woodbury"};

    std::string names; size_t rnd = 0; size_t rnd2 = 0; int i = 0;

i = rng() % 10; {
    rnd2 = rng() % std::size(nm3);
    if (type == 1) {
    rnd = rng() % std::size(nm2);
    names = nm2[rnd] + " " + nm3[rnd2];
    } else {
    rnd = rng() % std::size(nm1);
    names = nm1[rnd] + " " + nm3[rnd2];
    }
    return names;
    }
}
